dist: "bionic"
env:
   - CPPFLAGS=--coverage

install:
  - sudo bash bootstrap.sh

script:
  - configstore package test
  - sudo docker ps
  - sudo docker-compose -f ./docker-compose_local.yml run greencandle-unittest
