language: python
dist: "bionic"
python:
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "3.8-dev" # 3.8 development branch
  - "nightly"
env:
   - CPPFLAGS=--coverage

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libpoppler-cpp-dev pkg-config
  - pip install cpp-coveralls
  - sudo pip --version
  - sudo which pip
  - sudo python --version
  - sudo which python

jobs:
include:
  - stage: "Bootstrap"
    name: "Bootstrap"
    script: bash -x bootstrap.sh
  - stage: "Start DB"
    name: "Start DB"
    script: docker-compose up -d mysql redis
  - stage: "Tests"
    name: "Unit Tests"
    script: ls
  - script: ls
    name: "Integration Tests"
  - stage: deploy
    name: "Deploy to GCP"
    script: ls
