dist: "bionic"

install:
  - sudo bash install/bootstrap_dev.sh
  - sudo docker-compose -f ./install/docker-compose_unit.yml up -d mysql-unit redis-unit
  - source ~/.bashrc

before_script:
  - sleep 120

script:
  - configstore package test
  - sudo docker ps
  - sudo configstore package process_templates unit /etc
  - sudo mysqlcheck --host mysql -uroot -ppassword  --databases greencandle
  - sudo crontab config/template/gc-cron
  - PATH="/opt/pyenv/bin:$PATH" sudo pytest -k "not docker"
  - PATH="/opt/pyenv/bin:$PATH" sudo pytest -k "docker"
