dist: "bionic"
env:
   - CPPFLAGS=--coverage

install:
  - sudo bash install/bootstrap_dev.sh

script:
  - configstore package test
  - sudo docker ps
  - sudo docker-compose -f ./install/docker-compose_local.yml run greencandle-unittest
  - sudo mysqlcheck --host mysql -uroot -ppassword  --databases greencandle
  - sudo crontab config/template/gc-cron
