dist: bionic
install:
- sudo docker login -u "amrox" -p "$DPWD"
- sudo bash install/bootstrap_dev.sh
- sudo docker-compose -f ./install/docker-compose_unit.yml up -d mysql-unit redis-unit
before_script:
- sleep 120
script:
- configstore package test
- sudo docker ps
- sudo docker login -u "amrox" -p "$DPWD"
- sudo configstore package process_templates unit /etc
- sudo mysqlcheck --host mysql -uroot -ppassword  --databases greencandle
- cat  config/template/gc-cron |grep -v ^{| sudo crontab -
- cat config/template/*.json|jq
- sudo greencandle/tests/travis_tests.sh "not docker"
- sudo greencandle/tests/travis_tests.sh "docker"
notifications:
  slack:
    secure: QCEGE6ncguTVrd6omsYWjDrZty0XVJrf7VLK+sYqJci26H2iDF2PBqiLGibQr6UyPNKFStvAJKurhe6ORLxq8waGopEihfKByPgDksZkvJHvhSQNMjU859uWz4w/YZ1/45iA5REphzh5zQuUl7EM+AzwjsEagZJMHrkDB5NkRRD5i8fgMfLcuddPXAj1RwWjVGPcLmCIzjY9rJLNQBQHRjPOsTHtYStji20JRsqsZP4fNepI1F9eFOdS3ledwqnYdxeESOsa/VPhzpWtUnd1a0s7EwuhFK1E+C5iI+HfRSscewmuJbT6v31UDzScaAo7y5yHd/vjDjLgwfUZr6SFFqFOHxuxGSTQtOLyOM8t0pVZFvBGFSJbBD7QQ2PGw4/C2epmEwb8u+KtpZ4rFVCG9IlqWXtXje0XPl8/lFK0Tc4PAxHUUjnagbf1VrnIwMPYYp/RIwxCs/qbu0BChdZqZdKJIhEkDwUVxEI8UMRojgOMFK+kdsp+jcYlTPH/wghv7+rLAYE02W3x3yebCP+TyJmurdXe689OUob8H8490UWzwmRR5HjtWv6GTEfx03p7VxYxso+CF9KXwNAtKTKORnlIwy8BfYvUHVK7jNI9QMbmZu8vikKqAmfkE58zteKdx6beyX5tR2o7GQv/LwK5ov4JqhCB49UBiNI+9+2WaUo=
env:
  global:
  - secure: TlDyxXMu3gv69Dk174z0YceiEJY29JZcaSYDcE/5NJpyejlwq3/Y2WXTAP8DUS/7L/U5aO1lZ5aDY45Sf2fMke3GVW90K9P78VFF+6FF+F7NvvAT/wkYDSKFhGjE6SIjaVpmh6KrAGxVsVWVMePExu8QCenfOdsII9zkjXNuB4jSbdDuFZwYGp9GqNmCvFPDMzdq/D57G9qp08skObRgC2QZEGRbURGdlkpp8hKdvD5toFlThkMtSzBAToY7KqdCI9TYtA/PmbVyO+hHli1ZbnRYl+xiKxIlBdqoUxpvDBaNoE6huMq9W8GSkryuFf1JS3TyxWrD4UbeYOE7twDK8tJy7n3atsVohgME4bZUFi2puox5HbdENzJewOPBm5Zi+TyhVrW3U3iiJpEm1oxXaNunUpa8jeSxW+CBBMQjBod8FtZrakL0HJHGv/d9FAH/25tr+XO6iVi8mvMuj8lZTxyx4rK7wxvBJc8NCfHJxd6X5bVDLEGRpr0YDqVrjWVNVVK8CJ74VHjGD6AMpPKeJJsIJKt+l5S8taZTYPJWvcDZEq2EN6ygKGQn1DJP5pGKa8kE4nX8WFVuz0Utrpej1VJBT1N8aoizdI2Bhz2VihsO0BqPuGYO9wQKCTx/lXFwMC/MohSKmnnUNTbcDLIeqR3IBY+TEo81Gl7+JYSNmh4=
