dist: "bionic"
env:
   - CPPFLAGS=--coverage

install:
  - sudo bash bootstrap.sh

script:
  - sudo docker-compose up -d mysql redis
  - sudo docker ps
  - sudo docker-compose up greencandle-unittest
