dist: "bionic"
env:
   - CPPFLAGS=--coverage

install:
  - sudo bash bootstrap.sh

script:
  - configstore package test
  - sudo docker-compose up -d mysql-local redis-local
  - sudo docker ps
  - sudo docker-compose run greencandle-unittest
