language: python
dist: "bionic"
python:
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "3.8-dev" # 3.8 development branch
  - "nightly"
env:
   - CPPFLAGS=--coverage

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libpoppler-cpp-dev pkg-config
  - pip install cpp-coveralls

# command to install dependencies
bootstrap:
  - sudo bash -x bootstrap.sh

fix-pip:
  - sudo curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - sudo python /tmp/get-pip.py --force-reinstall
  - sudo pip install pip=9.0.1
  - sudo rm -rf /tmp/get-pip.py

install:
  - sudo bash -x gc-install.sh

check:
  - sudo docker ps

script:
  ls
