dist: "bionic"

install:
  - sudo bash install/bootstrap_dev.sh
  - sudo docker-compose -f ./install/docker-compose_unit.yml up -d mysql-unit redis-unit

before_script:
  - sleep 120

script:
  - configstore package test
  - sudo docker ps
  - sudo configstore package process_templates unit /etc
  - sudo mysqlcheck --host mysql -uroot -ppassword  --databases greencandle
  - cat  config/template/gc-cron |grep -v ^{| sudo crontab -
  - sudo greencandle/tests/travis_tests.sh "not docker"
  - sudo greencandle/tests/travis_tests.sh "docker"
