dist: "bionic"
env:
   - CPPFLAGS=--coverage

jobs:
  include:
    - stage: "Bootstrap"
      name: "Bootstrap"
      script: bash -x bootstrap.sh
    - stage: "Start DB"
      name: "Start DB"
      script: docker-compose up -d mysql redis
    - stage: "Tests"
      name: "Unit Tests"
      script: ls
    - script: ls
      name: "Integration Tests"
    - stage: deploy
      name: "Deploy to GCP"
      script: ls
