language: python
dist: "bionic"
python:
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "3.8-dev" # 3.8 development branch
  - "nightly"
env:
   - CPPFLAGS=--coverage

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libpoppler-cpp-dev pkg-config
  - pip install cpp-coveralls

# command to install dependencies
bootstrap:
  - sudo bash bootstrap.sh
install:
  - sudo bash gc-install.sh
check:
  - sudo docker ps
script:
  ls
