dist: "bionic"

install:
  - sudo bash install/bootstrap_dev.sh
  - sudo docker-compose -f ./install/docker-compose_local.yml up -d mysql-local redis-local

before_script:
  - sleep 120

script:
  - configstore package test
  - sudo docker ps
  - sudo configstore package process_templates test/unit /etc
  - sudo mysqlcheck --host mysql -uroot -ppassword  --databases greencandle
  - sudo crontab config/template/gc-cron
  - sudo pytest -k "not docker"
  - sudo pytest -k "docker"
