version: "3.1"
services:

  redis-local:
    container_name: redis-local
    hostname: redis-local
    image: gc-redis
    ports:
      - 6379:6379
    restart: on-failure
    links:
      - mysql-local:mysql
    healthcheck:
      test: redis-cli ping
      interval: 1m
      timeout: 2s
      retries: 5

  mysql-local:
    container_name: mysql-local
    hostname: mysql-local
    image: gc-mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - CONFIG_ENV=test
    restart: on-failure
    healthcheck:
      test: echo 'SELECT version();'| mysql -uroot -ppassword
      interval: 1m
      timeout: 2s
      retries: 5

  greencandle-unittest:
    container_name: unittest
    hostname: unittest
    image: amrox/greencandle
    entrypoint: /docker-entrypoint.sh python -m unittest
    links:
      - mysql-local:mysql
      - redis-local:redis
    working_dir: /srv/greencandle
    depends_on:
      - redis-local
      - mysql-local
    environment:
      - CONFIG_ENV=test/unit
    volumes:
      - ./:/srv/greencandle
