version: "3.1"
services:

  redis:
    image: gc-redis
    ports:
      - 6379:6379
    restart: on-failure
    links:
      - mysql
    healthcheck:
      test: redis-cli ping
      interval: 1m
      timeout: 2s
      retries: 5

  mysql:
    image: gc-mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    restart: on-failure
    healthcheck:
      test: echo 'SELECT version();'| mysql -uroot -ppassword
      interval: 1m
      timeout: 2s
      retries: 5

  greencandle-test:
    image: greencandle
    entrypoint: backend --use-redis --test
    links:
      - mysql
    depends_on:
      - mysql
      - redis
    healthcheck:
      test: find /var/run/  -mmin -2 -name greencandle 2>&1 |grep -q greencandle ||exit 1
      interval: 1m
      timeout: 2s
      retries: 5
    volumes:
      - ./test:/tmp

  cron:
    image: greencandle
    entrypoint: cron -f
    links:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis
    volumes:
      - /data:/data

  webserver:
     image: webserver
     ports:
       - 80:80
     entrypoint: bash -c nginx|more
     volumes:
       - /data:/data
