version: "3.1"
services:

  redis:
    container_name: redis
    hostname: redis
    image: amrox/gc-redis
    ports:
      - 6379:6379
    restart: on-failure
    links:
      - mysql
    healthcheck:
      test: redis-cli ping
      interval: 1m
      timeout: 2s
      retries: 5

  mysql:
    container_name: mysql
    hostname: mysql
    image: amrox/gc-mysql
    entrypoint: /docker-entrypoint.sh mysqld
    ports:
      - 3306:3306
    environment:
      - CONFIG_ENV=prod
      - MYSQL_ROOT_PASSWORD=password
    restart: on-failure
    healthcheck:
      test: echo 'SELECT version();'| mysql -uroot -ppassword
      interval: 1m
      timeout: 2s
      retries: 5
    volumes:
      - /root/.aws:/root/.aws

4ma-btc:
    container_name: 4ma-btc
    hostname: 4ma-btc
    image: amrox/greencandle
    entrypoint: /docker-entrypoint.sh backend --test
    links:
      - mysql
    depends_on:
      - mysql
      - redis
    environment:
      - CONFIG_ENV=prod/4MA/btc
      - HOST=$HOSTNAME
    healthcheck:
      test: find /var/run/  -mmin -2 -name greencandle 2>&1 |grep -q greencandle ||exit 1
      interval: 1m
      timeout: 2s
      retries: 5
    volumes:
      - ./test:/tmp
      - /root/.aws:/root/.aws

4ma-usdt:
    container_name: 4ma-usdt
    hostname: 4ma-usdt
    image: amrox/greencandle
    entrypoint: /docker-entrypoint.sh backend --test
    links:
      - mysql
    depends_on:
      - mysql
      - redis
    environment:
      - CONFIG_ENV=prod/4MA/usdt
      - HOST=$HOSTNAME
    healthcheck:
      test: find /var/run/  -mmin -2 -name greencandle 2>&1 |grep -q greencandle ||exit 1
      interval: 1m
      timeout: 2s
      retries: 5
    volumes:
      - ./test:/tmp
      - /root/.aws:/root/.aws

  4ma-eth:
    container_name: 4ma-eth
    hostname: 4ma-eth
    image: amrox/greencandle
    entrypoint: /docker-entrypoint.sh backend --test
    links:
      - mysql
    depends_on:
      - mysql
      - redis
    environment:
      - CONFIG_ENV=prod/4MA/eth
      - HOST=$HOSTNAME
    healthcheck:
      test: find /var/run/  -mmin -2 -name greencandle 2>&1 |grep -q greencandle ||exit 1
      interval: 1m
      timeout: 2s
      retries: 5
    volumes:
      - ./test:/tmp
      - /root/.aws:/root/.aws

  30mRSI:
    container_name: 30mRSI
    hostname: 30mRSI
    image: amrox/greencandle
    entrypoint: /docker-entrypoint.sh backend --test
    links:
      - mysql
    depends_on:
      - mysql
      - redis
    environment:
      - CONFIG_ENV=prod/30mRSI
      - HOST=$HOSTNAME
    healthcheck:
      test: find /var/run/  -mmin -2 -name greencandle 2>&1 |grep -q greencandle ||exit 1
      interval: 1m
      timeout: 2s
      retries: 5
    volumes:
      - ./test:/tmp
      - /root/.aws:/root/.aws

  cron:
    container_name: cron
    environment:
      - CONFIG_ENV=prod
      - HOST=$HOSTNAME
    hostname: cron
    image: amrox/greencandle
    entrypoint: /docker-entrypoint.sh cron -f
    links:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis
    healthcheck:
      test: find /var/run/  -mmin -2 -name cron 2>&1 |grep -q greencandle ||exit 1
      interval: 1m
      timeout: 2s
      retries: 5
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws

  webserver:
     container_name: webserver
     hostname: webserver
     image: amrox/webserver
     healthcheck:
       test: service nginx status || exit 1
       interval: 5m
       timeout: 5s
       retries: 5
     environment:
       - CONFIG_ENV=prod
     ports:
       - 80:80
     links:
       - dashboard:dashboard
     entrypoint: /docker-entrypoint.sh nginx -g 'daemon off;'
     volumes:
       - /data:/data
       - /root/.aws:/root/.aws

  dashboard:
    container_name: dashboard
    hostname: dashboard
    image: visibilityspots/smashing
    ports:
      - 8080:3030
    healthcheck:
      test: curl --fail 127.1:3030/dashboard/gc || exit 1
      interval: 10m
      timeout: 5s
      retries: 5
    environment:
      - GEMS=mysql2
    entrypoint: /run.sh
    links:
      - mysql:mysql
    volumes:
      - /srv/greencandle/dashboard/dashboards:/dashboards
      - /srv/greencandle/dashboard/jobs:/jobs
      - /srv/greencandle/dashboard/widgets:/widgets
      - /srv/greencandle/dashboard/config:/config
      - /srv/greencandle/dashboard/assets:/assets
