version: "3.1"
services:

  webserver:
     container_name: webserver
     hostname: webserver
     image: webserver
     entrypoint: /docker-entrypoint.sh nginx -g 'daemon off;'
     healthcheck:
       test: service nginx status || exit 1
       interval: 5m
       timeout: 5s
       retries: 5
     environment:
       - CONFIG_ENV=test
     ports:
       - 80:80
     links:
       - mysql-local:mysql
       - redis-local:redis
       - dashboard:dashboard
     restart: on-failure
     volumes:
       - /data:/data
       - /root/.aws:/root/.aws

  dashboard:
    container_name: dashboard
    hostname: dashboard
    image: visibilityspots/smashing
    healthcheck:
      test: curl --fail 127.1:3030/dashboard/gc || exit 1
      interval: 10m
      timeout: 5s
      retries: 5
    ports:
      - 8080:3030
    environment:
      - GEMS=mysql2
    restart: on-failure
    entrypoint: /run.sh
    links:
      - mysql-local:mysql
    volumes:
      - /srv/greencandle/dashboard/dashboards:/dashboards
      - /srv/greencandle/dashboard/jobs:/jobs
      - /srv/greencandle/dashboard/widgets:/widgets
      - /srv/greencandle/dashboard/config:/config
      - /srv/greencandle/dashboard/assets:/assets

  redis-local:
    container_name: redis-local
    hostname: redis-local
    image: gc-redis
    ports:
      - 6379:6379
    restart: on-failure
    links:
      - mysql-local:mysql
    healthcheck:
      test: redis-cli ping
      interval: 1m
      timeout: 2s
      retries: 5

  mysql-local:
    container_name: mysql-local
    hostname: mysql-local
    image: gc-mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - CONFIG_ENV=test
    restart: on-failure
    healthcheck:
      test: echo 'SELECT version();'| mysql -uroot -ppassword
      interval: 1m
      timeout: 2s
      retries: 5

  greencandle-unittest:
    container_name: unittest
    hostname: unittest
    image: amrox/greencandle
    entrypoint: /docker-entrypoint.sh python -m unittest
    links:
      - mysql-local:mysql
      - redis-local:redis
    working_dir: /srv/greencandle
    depends_on:
      - redis-local
      - mysql-local
    environment:
      - CONFIG_ENV=test/unit
    volumes:
      - ./:/srv/greencandle
