apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: test 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: test 
    spec:
      containers:
        - name: test 
          image: cultbeauty.azurecr.io/test
          ports:
          - containerPort: 2000