version: "3.1"
services:

  cadvisor:
    container_name: cadvisor
    hostname: cadvisor
    image: gcr.io/google_containers/cadvisor:v0.35.0
    restart: always
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs
      - /var/run:/var/run
      - /sys:/sys
      - /var/lib/docker:/var/lib/docker
      - /dev/disk:/dev/disk

  cron:
    container_name: cron
    environment:
      - CONFIG_ENV=test/cron
      - HOST=$HOSTNAME
    hostname: cron
    image: amrox/greencandle
    restart: always
    entrypoint: /docker-entrypoint.sh cron -f
    links:
      - mysql-local:mysql
      - redis-local:redis
    depends_on:
      - mysql-local
      - redis-local
    healthcheck:
      test: find /var/run/  -mmin -2 -name cron 2>&1 |grep -q cron ||exit 1
      interval: 1m
      timeout: 2s
      retries: 5
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws

  api:
    container_name: api
    environment:
      - CONFIG_ENV=test
      - HOST=$HOSTNAME
    hostname: api
    image: amrox/greencandle
    restart: always
    entrypoint: /docker-entrypoint-api.sh api --test
    links:
      - mysql-local:mysql
      - redis-local:redis
    ports:
      - 5000:5000
    depends_on:
      - mysql-local
      - redis-local
    healthcheck:
      test: find /var/run/  -mmin -2 -name api 2>&1 |grep -q api || exit 1
      interval: 1m
      timeout: 2s
      retries: 5
    volumes:
      - /data:/data

  webserver:
     container_name: webserver
     hostname: webserver
     image: amrox/webserver
     entrypoint: /docker-entrypoint.sh nginx -g 'daemon off;'
     healthcheck:
       test: service nginx status || exit 1
       interval: 1m
       timeout: 1s
       retries: 5
     environment:
       - CONFIG_ENV=test
       - HOST=$HOSTNAME
     ports:
       - 7777:7777
     links:
       - mysql-local:mysql
       - redis-local:redis
       - api
     restart: always
     volumes:
       - /data:/data
       - /root/.aws:/root/.aws
     depends_on:
      - cadvisor
      - api

  redis-local:
    container_name: redis-local
    hostname: redis-local
    image: amrox/gc-redis
    ports:
      - 6379:6379
    restart: always
    links:
      - mysql-local:mysql
    healthcheck:
      test: redis-cli ping
      interval: 1m
      timeout: 2s
      retries: 5

  mysql-local:
    container_name: mysql-local
    hostname: mysql-local
    image: amrox/gc-mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - CONFIG_ENV=test
    restart: always
    healthcheck:
      test: echo 'SELECT version();'| mysql -uroot -ppassword
      interval: 1m
      timeout: 2s
      retries: 5
