version: "3.1"
services:

  gen-be-logwatch:
    container_name: gen-be-logwatch
    hostname: gen-be-logwatch
    image: amrox/greencandle:${TAG}
    restart: always
    entrypoint: /docker-entrypoint-alert.sh /usr/local/bin/logwatch
    environment:
      - CONFIG_ENV=stag/fe/cron
      - HOST=$HOSTNAME
    volumes:
      - /var/log:/var/log
      - /root/.aws:/root/.aws
    healthcheck:
      test: ls /var/log/syslog
      interval: 1m
      timeout: 2s
      retries: 5

  gen-fe-cadvisor:
    container_name: gen-fe-cadvisor
    hostname: gen-fe-cadvisor
    image: gcr.io/google_containers/cadvisor:v0.35.0
    restart: always
    volumes:
      - /:/rootfs
      - /var/run:/var/run
      - /sys:/sys
      - /var/lib/docker:/var/lib/docker
      - /dev/disk:/dev/disk
    healthcheck:
      test: "printf 'GET /healthz HTTP/1.1\r\nHost: localhost\r\n\r\n' | nc localhost 8080"
      interval: 1m
      timeout: 2s
      retries: 5

  stag-base-redis:
    container_name: stag-base-redis
    hostname: stag-base-redis
    image: amrox/gc-redis:${TAG}
    pull_policy: always
    restart: always
    links:
      - stag-base-mysql:mysql
    ports:
      - 6379:6379
    healthcheck:
      test: redis-cli ping
      interval: 1m
      timeout: 2s
      retries: 5
    volumes:
      - /var/run/systemd/journal/socket:/var/run/systemd/journal/socket
      - /root/.aws:/root/.aws
      - /root/.bash_history:/root/.bash_history

  stag-base-mysql:
    container_name: stag-base-mysql
    hostname: stag-base-mysql
    image: amrox/gc-mysql:${TAG}
    pull_policy: always
    entrypoint: /docker-entrypoint.sh mysqld
    environment:
      - CONFIG_ENV=stag
      - MYSQL_ROOT_PASSWORD=password
    restart: always
    ports:
      - 3306:3306
    healthcheck:
      test: echo 'SELECT version();'| mysql -uroot -ppassword
      interval: 1m
      timeout: 2s
      retries: 5
    volumes:
      - /var/run/systemd/journal/socket:/var/run/systemd/journal/socket
      - /root/.aws:/root/.aws
      - /root/.bash_history:/root/.bash_history

  stag-fe-api-dashboard:
    container_name: stag-fe-api-dashboard
    hostname: stag-fe-api-dashboard
    environment:
      - CONFIG_ENV=stag/fe/api
      - HOST=$HOSTNAME
    logging:
      driver: journald
    image: amrox/greencandle:${TAG}
    pull_policy: always
    restart: always
    entrypoint: /docker-entrypoint-api.sh api_dashboard
    links:
      - stag-base-mysql:mysql
      - stag-base-redis:redis
      - stag-be-api-router:router
    ports:
      - 5000
    depends_on:
      - stag-base-mysql
      - stag-base-redis
    healthcheck:
      test: curl -Isf http://127.1:5000/healthcheck
      interval: 1m
      timeout: 2s
      retries: 5
    volumes:
      - /data:/data
      - /dev/log:/dev/log
      - /root/.aws:/root/.aws
      - /var/run/systemd/journal/socket:/var/run/systemd/journal/socket
      - /root/.bash_history:/root/.bash_history

  stag-fe-cron:
    container_name: stag-fe-cron
    hostname: stag-fe-cron
    environment:
      - CONFIG_ENV=stag/fe/cron
      - HOST=$HOSTNAME
    image: amrox/greencandle:${TAG}
    pull_policy: always
    restart: always
    entrypoint: /docker-entrypoint.sh cron -f
    logging:
      driver: journald
    links:
      - stag-base-mysql:mysql
      - stag-base-redis:redis
    depends_on:
      - stag-base-mysql
      - stag-base-redis
    healthcheck:
      test: find /var/run/  -mmin -2 -name cron 2>&1 |grep -q cron ||exit 1
      interval: 1m
      timeout: 2s
      retries: 5
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/log:/dev/log
      - /var/run/systemd/journal/socket:/var/run/systemd/journal/socket
      - /root/.bash_history:/root/.bash_history

  stag-fe-webserver:
    container_name: stag-fe-webserver
    hostname: stag-fe-webserver
    image: amrox/webserver:${TAG}
    pull_policy: always
    restart: always
    healthcheck:
      test: service nginx status || exit 1
      interval: 5m
      timeout: 5s
      retries: 5
    environment:
      - CONFIG_ENV=stag
      - HOST=$HOSTNAME
    ports:
      - 8888:8888
    links:
      - gen-fe-cadvisor:cadvisor
      - stag-fe-api-dashboard:api_dash
      - stag-base-mysql:mysql
      - stag-base-redis:redis
    depends_on:
      - gen-fe-cadvisor
      - stag-base-mysql
      - stag-base-redis
    entrypoint: /docker-entrypoint.sh nginx -g 'daemon off;'
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws
      - /root/.bash_history:/root/.bash_history

  stag-fe-api-web:
    container_name: stag-fe-api-web
    hostname: stag-fe-api-web
    image: amrox/webserver:${TAG}
    pull_policy: always
    restart: always
    healthcheck:
      test: service nginx status || exit 1
      interval: 5m
      timeout: 5s
      retries: 5
    environment:
      - CONFIG_ENV=stag/fe/api
      - HOST=$HOSTNAME
    ports:
      - 1111:1111
    links:
      - stag-be-api-router:router
      - stag-base-mysql:mysql
      - stag-base-redis:redis
    depends_on:
      - stag-base-mysql
      - stag-base-redis
    entrypoint: /docker-entrypoint-api2.sh nginx -g 'daemon off;'
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws
      - /root/.bash_history:/root/.bash_history

  stag-be-api-router:
    container_name: stag-be-api-router
    hostname: stag-be-api-router
    image: amrox/greencandle:${TAG}
    pull_policy: always
    restart: always
    healthcheck:
      test: curl -Isf http://127.1:1080/healthcheck
      interval: 5m
      timeout: 5s
      retries: 5
    environment:
      - CONFIG_ENV=stag
      - HOST=$HOSTNAME
    ports:
      - 1080
    links:
      - stag-be-alert:alert
      - stag-base-mysql:mysql
      - stag-base-redis:redis
      - stag-be-any:any
      - stag-be-any-short:any-short
    depends_on:
      - stag-be-alert
      - stag-base-mysql
      - stag-base-redis
      - stag-be-any
      - stag-be-any-short
    entrypoint: /docker-entrypoint.sh api_router --test
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws
      - /var/run/systemd/journal/socket:/var/run/systemd/journal/socket
      - /root/.bash_history:/root/.bash_history

  stag-be-5ma-api-btc:
    container_name: stag-be-5ma-api-btc
    hostname: stag-be-5ma-api-btc
    image: amrox/greencandle:${TAG}
    pull_policy: always
    restart: always
    entrypoint: /docker-entrypoint.sh backend_api --test
    logging:
      driver: journald
    environment:
      - HOST=$HOSTNAME
      - CONFIG_ENV=stag/5MA/api/btc
    ports:
      - 20000
    links:
      - stag-base-mysql:mysql
      - stag-base-redis:redis
    depends_on:
      - stag-base-mysql
      - stag-base-redis
    healthcheck:
      test: ls ||exit 1
      interval: 1m
      timeout: 2s
      retries: 5
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run/systemd/journal/socket:/var/run/systemd/journal/socket
      - /root/.bash_history:/root/.bash_history

  stag-be-5ma-api-usdt:
    container_name: stag-be-5ma-api-usdt
    hostname: stag-be-5ma-api-usdt
    image: amrox/greencandle:${TAG}
    pull_policy: always
    restart: always
    entrypoint: /docker-entrypoint.sh backend_api --test
    logging:
      driver: journald
    environment:
      - HOST=$HOSTNAME
      - CONFIG_ENV=stag/5MA/api/usdt
    ports:
      - 20000
    links:
      - stag-base-mysql:mysql
      - stag-base-redis:redis
    depends_on:
      - stag-base-mysql
      - stag-base-redis
    healthcheck:
      test: ls ||exit 1
      interval: 1m
      timeout: 2s
      retries: 5
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run/systemd/journal/socket:/var/run/systemd/journal/socket
      - /root/.bash_history:/root/.bash_history

  stag-be-5ma-api-eth:
    container_name: stag-be-5ma-api-eth
    hostname: stag-be-5ma-api-eth
    image: amrox/greencandle:${TAG}
    pull_policy: always
    restart: always
    entrypoint: /docker-entrypoint.sh backend_api --test
    logging:
      driver: journald
    environment:
      - HOST=$HOSTNAME
      - CONFIG_ENV=stag/5MA/api/eth
    ports:
      - 20000
    links:
      - stag-base-mysql:mysql
      - stag-base-redis:redis
    depends_on:
      - stag-base-mysql
      - stag-base-redis
    healthcheck:
      test: ls ||exit 1
      interval: 1m
      timeout: 2s
      retries: 5
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run/systemd/journal/socket:/var/run/systemd/journal/socket
      - /root/.bash_history:/root/.bash_history

  stag-be-any:
    container_name: stag-be-any
    hostname: stag-be-any
    image: amrox/greencandle:${TAG}
    pull_policy: always
    restart: always
    entrypoint: /docker-entrypoint.sh backend_api --test
    logging:
      driver: journald
    environment:
      - HOST=$HOSTNAME
      - CONFIG_ENV=stag/any
    ports:
      - 20000
    links:
      - stag-base-mysql:mysql
      - stag-base-redis:redis
    depends_on:
      - stag-base-mysql
      - stag-base-redis
    healthcheck:
      test: ls ||exit 1
      interval: 1m
      timeout: 2s
      retries: 5
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run/systemd/journal/socket:/var/run/systemd/journal/socket
      - /root/.bash_history:/root/.bash_history

stag-be-any-short:
    container_name: stag-be-any-short
    hostname: stag-be-any-short
    image: amrox/greencandle:${TAG}
    pull_policy: always
    restart: always
    entrypoint: /docker-entrypoint.sh backend_api --test
    logging:
      driver: journald
    environment:
      - HOST=$HOSTNAME
      - CONFIG_ENV=stag/any/short
    ports:
      - 20000
    links:
      - stag-base-mysql:mysql
      - stag-base-redis:redis
    depends_on:
      - stag-base-mysql
      - stag-base-redis
    healthcheck:
      test: ls ||exit 1
      interval: 1m
      timeout: 2s
      retries: 5
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run/systemd/journal/socket:/var/run/systemd/journal/socket
      - /root/.bash_history:/root/.bash_history

  stag-be-alert:
    container_name: stag-be-alert
    hostname: stag-be-alert
    image: amrox/alert:latest
    pull_policy: always
    restart: always
    entrypoint: /docker-entrypoint-alert.sh /srv/greencandle/alert/webhook.py
    ports:
      - 20000
    healthcheck:
      test: ls || exit 1
      interval: 1m
      timeout: 2s
      retries: 5
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/snd:/dev/snd
    environment:
      - HOST=$HOSTNAME
      - CONFIG_ENV=stag
    volumes:
      - /root/.aws:/root/.aws
      - /run/dbus/:/run/dbus/
      - /dev/shm:/dev/shm
      - /run/user:/run/user
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /var/run/dbus:/var/run/dbu
      - /etc/localtime:/etc/localtime:ro
      - /root/.bash_history:/root/.bash_history

