FROM python:3.7.0

RUN apt-get update
RUN apt-get -y install vim cron netcat default-mysql-client bsdmainutils libssl-dev libsystemd-dev xvfb xauth iceweasel --no-install-recommends
RUN apt-get clean; apt-get autoclean; rm -rf /var/lib/apt/lists/*
RUN wget "https://www.dropbox.com/sh/l22jyonei087h4o/AAAVa_B_sDXtWZu17RzazsA2a/geckodriver-v0.26.0-linux64.tar.gz?dl=0" -O /tmp/geckodriver-v0.26.0-linux64.tar.gz
RUN tar zxvf /tmp/geckodriver-v0.26.0-linux64.tar.gz -C /usr/local/bin
RUN rm -rf /tmp/geckodriver-v0.26.0-linux64.tar.gz
RUN wget "https://www.dropbox.com/sh/l22jyonei087h4o/AAChfqr_j4ydTDjILz0Q62Y2a/configstore-2.5.0-linux-amd64.tar.gz?dl=0" -O /tmp/configstore-2.5.0-linux-amd64.tar.gz
RUN tar zxvf /tmp/configstore-2.5.0-linux-amd64.tar.gz -C /usr/local/bin
RUN rm -rf /tmp/configstore-2.5.0-linux-amd64.tar.gz
RUN wget "https://www.dropbox.com/sh/l22jyonei087h4o/AABz_MIHb3a8ZPWv0gbhkDAia/ta-lib-0.4.0-src.tar.gz?dl=0" -O /tmp/ta-lib-0.4.0-src.tar.gz
RUN tar zxvf /tmp/ta-lib-0.4.0-src.tar.gz -C /tmp
RUN cd /tmp/ta-lib; ./configure --prefix=/usr; make; make install
RUN cd /; rm -rf /tmp/ta-lib /tmp/ta-lib-0.4.0-src.tar.gz

RUN pip install cython redis-dump-load urllib3==1.24.3 APScheduler==3.6.1 argcomplete>=1.9.3 coinbase==2.0.6 configparser==3.5.0 Babel==2.9.1 CurrencyConverter==0.16.1 Flask>=0.12.3 docker==5.0.3 lib==3.0.0 mysqlclient==1.3.12 oauth==1.0.1 pandas==1.0.1 numpy==1.16.0 Pillow>=6.2.2 plotly==4.1.1 python_resize_image==1.1.11 PyVirtualDisplay==1.3.2 redis==2.10.6 requests==2.22.0 scipy==1.4.1 selenium==3.8.1 setproctitle==1.1.10 simplejson==3.13.2 ta-lib==0.4.14 str2bool==1.1 openpyxl==2.6.3 notify-run==0.0.13 xlrd==1.2.0 requests-unixsocket==0.2.0 pylint==2.4.4 waitress six==1.12 systemd==0.16.1 tzlocal==2.1b1 cryptocompare==0.7.3 pandas_ta==0.2.23b0 pyyaml==5.4.1 setuptools-rust setuptools==45.1.0 pip==9.0.1 numpy==1.16.0 ccxt==1.50.10 cryptography==3.3.1 gitpython pytest

CMD ["python"]
