FROM  python:3.9.2-buster
copy . .

RUN apt update && \
    apt-get -y install mpg321 gstreamer-1.0 libgirepository1.0-dev gcc libcairo2-dev pkg-config python3-dev gir1.2-gtk-3.0 && \
    pip install -r ./alert/requirements.txt

CMD ["webhook.py"]
ENTRYPOINT ["python3"]
