services:
  stream-fe_binance:
    container_name: stream-fe_binance
    hostname: stream-fe_binance
    image: amrox/greencandle:${TAG}
    mem_limit: 500M
    pull_policy: always
    restart: on-failure
    entrypoint: /docker-entrypoint.sh stream_binance
    logging:
      driver: syslog
      options:
        tag: {{.Name}}
        syslog-facility: local7
    environment:
      - CONFIG_ENV=data/be/get_data/
    healthcheck:
      test: echo
      start_period: 5m
      interval: 5m
      timeout: 10s
      retries: 5
    ports:
      - 6000:5000
    volumes:
      - /mnt:/mnt
      - /data:/data
      - /var/local:/var/local
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run/:/var/run

  stream-fe_5m:
    container_name: stream-fe_5m
    hostname: stream-fe_5m
    image: amrox/greencandle:${TAG}
    mem_limit: 200M
    pull_policy: always
    restart: on-failure
    entrypoint: /docker-entrypoint.sh stream_data
    logging:
      driver: syslog
      options:
        tag: {{.Name}}
        syslog-facility: local7
    environment:
      - CONFIG_ENV=data/be/get_data/5m
    healthcheck:
      test: /mnt/nagios_checks/check_milliepoch -u http://127.1:5000 -w 360 -c 420 || bash -c 'kill -s 15 -1 && (sleep 10; kill -s 9 -1)'
      start_period: 5m
      interval: 5m
      timeout: 10s
      retries: 5
    ports:
      - 5002:5000
    volumes:
      - /mnt:/mnt
      - /data:/data
      - /var/local:/var/local
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run/:/var/run

  stream-fe_15m:
    container_name: stream-fe_15m
    hostname: stream-fe_15m
    image: amrox/greencandle:${TAG}
    mem_limit: 200M
    pull_policy: always
    restart: on-failure
    entrypoint: /docker-entrypoint.sh stream_data
    logging:
      driver: syslog
      options:
        tag: {{.Name}}
        syslog-facility: local7
    environment:
      - CONFIG_ENV=data/be/get_data/15m
    healthcheck:
      test: /mnt/nagios_checks/check_milliepoch -u http://127.1:5000 -w 43500 -c 43560 || bash -c 'kill -s 15 -1 && (sleep 10; kill -s 9 -1)'
      start_period: 10m
      interval: 10m
      timeout: 30s
      retries: 5
    ports:
      - 5003:5000
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run/:/var/run
      - /mnt:/mnt

  stream-fe_30m:
    container_name: stream-fe_30m
    hostname: stream-fe_30m
    image: amrox/greencandle:${TAG}
    mem_limit: 200M
    pull_policy: always
    restart: on-failure
    entrypoint: /docker-entrypoint.sh stream_data
    logging:
      driver: syslog
      options:
        tag: {{.Name}}
        syslog-facility: local7
    environment:
      - CONFIG_ENV=data/be/get_data/30m
    healthcheck:
      test: /mnt/nagios_checks/check_milliepoch -u http://127.1:5000 -w 43500 -c 43560 || bash -c 'kill -s 15 -1 && (sleep 10; kill -s 9 -1)'
      start_period: 10m
      interval: 10m
      timeout: 30s
      retries: 5
    ports:
      - 5004:5000
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run/:/var/run
      - /mnt:/mnt

  stream-fe_1h:
    container_name: stream-fe_1h
    hostname: stream-fe_1h
    image: amrox/greencandle:${TAG}
    mem_limit: 200M
    pull_policy: always
    restart: on-failure
    entrypoint: /docker-entrypoint.sh stream_data
    logging:
      driver: syslog
      options:
        tag: {{.Name}}
        syslog-facility: local7
    environment:
      - CONFIG_ENV=data/be/get_data/1h
    healthcheck:
      test: /mnt/nagios_checks/check_milliepoch -u http://127.1:5000 -w 3660 -c 3720 || bash -c 'kill -s 15 -1 && (sleep 10; kill -s 9 -1)'
      interval: 5m
      start_period: 5m
      timeout: 10s
      retries: 5
    ports:
      - 5005:5000
    volumes:
      - /mnt:/mnt
      - /data:/data
      - /var/local:/var/local
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run/:/var/run

  stream-fe_4h:
    container_name: stream-fe_4h
    hostname: stream-fe_4h
    image: amrox/greencandle:${TAG}
    mem_limit: 200M
    pull_policy: always
    restart: on-failure
    entrypoint: /docker-entrypoint.sh stream_data
    logging:
      driver: syslog
      options:
        tag: {{.Name}}
        syslog-facility: local7
    environment:
      - CONFIG_ENV=data/be/get_data/4h
    healthcheck:
      test: /mnt/nagios_checks/check_milliepoch -u http://127.1:5000 -w 14400 -c 14460 || bash -c 'kill -s 15 -1 && (sleep 10; kill -s 9 -1)'
      start_period: 5m
      interval: 5m
      timeout: 30s
      retries: 5
    ports:
      - 5006:5000
    volumes:
      - /mnt:/mnt
      - /data:/data
      - /var/local:/var/local
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run/:/var/run

  stream-fe_12h:
    container_name: stream-fe_12h
    hostname: stream-fe_12h
    image: amrox/greencandle:${TAG}
    mem_limit: 200M
    pull_policy: always
    restart: on-failure
    entrypoint: /docker-entrypoint.sh stream_data
    logging:
      driver: syslog
      options:
        tag: {{.Name}}
        syslog-facility: local7
    environment:
      - CONFIG_ENV=data/be/get_data/12h
    healthcheck:
      test: /mnt/nagios_checks/check_milliepoch -u http://127.1:5000 -w 43500 -c 43560 || bash -c 'kill -s 15 -1 && (sleep 10; kill -s 9 -1)'
      start_period: 10m
      interval: 10m
      timeout: 30s
      retries: 5
    ports:
      - 5007:5000
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run/:/var/run
      - /mnt:/mnt

  stream-fe_1d:
    container_name: stream-fe_1d
    hostname: stream-fe_1d
    image: amrox/greencandle:${TAG}
    mem_limit: 200M
    pull_policy: always
    restart: on-failure
    entrypoint: /docker-entrypoint.sh stream_data
    logging:
      driver: syslog
      options:
        tag: {{.Name}}
        syslog-facility: local7
    environment:
      - CONFIG_ENV=data/be/get_data/1d
    healthcheck:
      test: /mnt/nagios_checks/check_milliepoch -u http://127.1:5000 -w 43500 -c 43560 || bash -c 'kill -s 15 -1 && (sleep 10; kill -s 9 -1)'
      start_period: 10m
      interval: 10m
      timeout: 30s
      retries: 5
    ports:
      - 5008:5000
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run/:/var/run
      - /mnt:/mnt
