services:
  config-be-manual:
    container_name: config-be-manual
    environment:
      - CONFIG_ENV=config
      - DB=true
    hostname: config-be-manual
    working_dir: /data/scripts
    image: amrox/greencandle:${TAG}
    restart: always
    entrypoint: /docker-entrypoint.sh "tail -f /dev/null"
    links:
      - config-base-mysql:mysql
      - config-base-redis:redis
    depends_on:
      - config-base-mysql
      - config-base-redis
    healthcheck:
      test: ls || exit 1
      interval: 5m
      timeout: 10s
      retries: 5
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws

  config-fe-api-config:
    container_name: config-fe-api-config
    environment:
      - CONFIG_ENV=config
    hostname: config-fe-api-config
    working_dir: /data/scripts
    image: amrox/greencandle:${TAG}
    restart: always
    entrypoint: /docker-entrypoint.sh api_config
    links:
      - config-base-redis:redis
    depends_on:
      - config-base-redis
    healthcheck:
      test: curl -Isf http://127.1:6000/healthcheck
      interval: 5m
      timeout: 10s
      retries: 5
    ports:
      - 6000:6000
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws

  config-base-redis:
    container_name: config-base-redis
    hostname: config-base-redis
    image: redis/redis-stack
    ports:
      - 6385:6379
    environment:
      - CONFIG_ENV=config
    restart: always
    links:
      - config-base-mysql:mysql
    healthcheck:
      test: redis-cli ping
      interval: 5m
      timeout: 10s
      retries: 5

  config-base-mysql:
    container_name: config-base-mysql
    hostname: config-base-mysql
    image: amrox/gc-mysql:${TAG}
    ports:
      - 3312:3306
    entrypoint: /docker-entrypoint.sh mysqld
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - CONFIG_ENV=config
      - DB=true
    restart: always
    healthcheck:
      test: echo 'SELECT version();'| mysql -uroot -ppassword
      interval: 5m
      timeout: 10s
      retries: 5
