FROM  amrox/python:3.9.2-buster-new
ADD ./alert /srv/alert
ADD ./config /opt/config
ADD ./install /opt/install

RUN pip install -r /srv/alert/requirements.txt
RUN mkdir /opt/output
RUN  cp /opt/install/docker-entrypoint.sh /
RUN useradd -ms /bin/bash dockeraudio
ARG BRANCH
ARG COMMIT
ARG DATE
ENV COMMIT_SHA=$COMMIT
ENV VERSION=$BRANCH
ENV BUILD_DATE=$DATE

CMD ["python", "/srv/alert/webhook.py"]
