services:
  backtest-fe-api-config:
    container_name: backtest-be-manual
    environment:
      - CONFIG_ENV=backtest
      - DB=true
    hostname: backtest-be-manual
    working_dir: /data/scripts
    image: amrox/greencandle:${TAG}
    restart: always
    entrypoint: /docker-entrypoint.sh api_config
    links:
      - backtest-base-redis:redis
    depends_on:
      - backtest-base-redis
    healthcheck:
      test: curl -Isf http://127.1:6000/healthcheck
      interval: 5m
      timeout: 10s
      retries: 5
    ports:
      - 6000:6000
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws

  backtest-base-redis:
    container_name: backtest-base-redis
    hostname: backtest-base-redis
    image: amrox/gc-redis:${TAG}
    ports:
      - 6384:6379
    environment:
      - CONFIG_ENV=backtest
    restart: always
    entrypoint: /docker-entrypoint.sh redis-server /etc/redis.conf
    healthcheck:
      test: redis-cli ping
      interval: 5m
      timeout: 10s
      retries: 5
