services:
  config-be-manual:
    container_name: config-be-manual
    environment:
      - CONFIG_ENV=config
      - DB=true
    logging:
      driver: syslog
      options:
        tag: "{{.Name}}"
        syslog-facility: local0
    hostname: config-be-manual
    working_dir: /data/scripts
    image: amrox/greencandle:${TAG}
    restart: unless-stopped
    entrypoint: /docker-entrypoint.sh "tail -f /dev/null"
    links:
      - config-base-mysql:mysql
      - config-base-redis:redis
    depends_on:
      - config-base-mysql
      - config-base-redis
    healthcheck:
      test: ls || exit 1
      interval: 5m
      timeout: 10s
      retries: 5
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws
  config-fe-api-config:
    container_name: config-fe-api-config
    environment:
      - CONFIG_ENV=config
    logging:
      driver: syslog
      options:
        tag: "{{.Name}}"
        syslog-facility: local0
    hostname: config-fe-api-config
    working_dir: /data/scripts
    image: amrox/greencandle:${TAG}
    restart: unless-stopped
    entrypoint: /docker-entrypoint.sh api_config
    links:
      - config-base-redis:redis
    depends_on:
      - config-base-redis
    healthcheck:
      test: curl -Isf http://127.1:6000/healthcheck
      interval: 5m
      timeout: 10s
      retries: 5
    ports:
      - 8000:6000
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws
  config-base-redis:
    container_name: config-base-redis
    hostname: config-base-redis
    image: amrox/gc-redis:${TAG}
    ports:
      - 6386:6379
    environment:
      - CONFIG_ENV=config
    restart: unless-stopped
    logging:
      driver: syslog
      options:
        tag: "{{.Name}}"
        syslog-facility: local0
    links:
      - config-base-mysql:mysql
    entrypoint: /usr/local/bin/docker-entrypoint.sh redis-server --loadmodule /srv/redis/rejson.so --save "30 1 300 100 60 10000"
    healthcheck:
      test: redis-cli ping
      interval: 5m
      timeout: 10s
      retries: 5
  config-base-mysql:
    container_name: config-base-mysql
    hostname: config-base-mysql
    image: amrox/gc-mysql:${TAG}
    ports:
      - 3312:3306
    entrypoint: /docker-entrypoint.sh mysqld
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - CONFIG_ENV=config
      - DB=true
    restart: unless-stopped
    logging:
      driver: syslog
      options:
        tag: "{{.Name}}"
        syslog-facility: local0
    healthcheck:
      test: echo 'SELECT version();'| mysql -uroot -ppassword
      interval: 5m
      timeout: 10s
      retries: 5
  config-fe-cron:
    container_name: config-fe-cron
    hostname: config-fe-cron
    environment:
      - CONFIG_ENV=config
      - DB=true
    image: amrox/greencandle:${TAG}
    mem_limit: 2G
    pull_policy: always
    restart: unless-stopped
    entrypoint: /docker-entrypoint.sh "touch /var/log/cron.log && cron && tail -f /var/log/cron.log"
    logging:
      driver: syslog
      options:
        tag: "{{.Name}}"
        syslog-facility: local0
    links:
      - config-base-mysql:mysql
      - config-base-redis:redis
    depends_on:
      - config-base-mysql
      - config-base-redis
    healthcheck:
      test: find /var/run/  -mmin -2 -name cron 2>&1 |grep -q cron ||exit 1
      interval: 5m
      timeout: 10s
      retries: 5
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.bash_history:/root/.bash_history
  config-be-logwatch:
    container_name: config-be-logwatch
    hostname: config-be-logwatch
    image: amrox/greencandle:${TAG}
    mem_limit: 4G
    restart: unless-stopped
    entrypoint: /docker-entrypoint.sh /usr/local/bin/logwatch
    environment:
      - CONFIG_ENV=config
      - DB=false
    volumes:
      - /var/log:/var/log
      - /root/.aws:/root/.aws
      - /var/run:/var/run
    healthcheck:
      test: ls /var/log/gc_config.log
      interval: 5m
      timeout: 10s
      retries: 5
