FROM amrox/mariadb:10.8


RUN apt-get update \
   && apt-get install -y cron bash wget nginx-extras netcat vim
RUN [ ! -f /usr/local/bin/configstore ] && \
    wget "http://local.amrox.loc/files/configstore-2.5.0-linux-amd64.tar.gz" \
    -O /tmp/configstore-2.5.0-linux-amd64.tar.gz && \
    tar zxvf /tmp/configstore-2.5.0-linux-amd64.tar.gz -C /usr/local/bin && \
    rm -rf /tmp/configstore-2.5.0-linux-amd64.tar.gz
RUN sudo sed -i '/skip_name_resolve/d' /etc/mysql/mariadb.cnf;
