FROM python:3.9.0

RUN apt-get update
RUN apt-get -y install vim cron netcat default-mysql-client bsdmainutils libssl-dev libsystemd-dev xvfb xauth iceweasel --no-install-recommends
RUN apt-get clean; apt-get autoclean; rm -rf /var/lib/apt/lists/*
RUN wget "https://www.dropbox.com/sh/l22jyonei087h4o/AAAVa_B_sDXtWZu17RzazsA2a/geckodriver-v0.26.0-linux64.tar.gz?dl=0" -O /tmp/geckodriver-v0.26.0-linux64.tar.gz
RUN tar zxvf /tmp/geckodriver-v0.26.0-linux64.tar.gz -C /usr/local/bin
RUN rm -rf /tmp/geckodriver-v0.26.0-linux64.tar.gz
RUN wget "https://www.dropbox.com/sh/l22jyonei087h4o/AAChfqr_j4ydTDjILz0Q62Y2a/configstore-2.5.0-linux-amd64.tar.gz?dl=0" -O /tmp/configstore-2.5.0-linux-amd64.tar.gz
RUN tar zxvf /tmp/configstore-2.5.0-linux-amd64.tar.gz -C /usr/local/bin
RUN rm -rf /tmp/configstore-2.5.0-linux-amd64.tar.gz
RUN wget "https://www.dropbox.com/sh/l22jyonei087h4o/AABz_MIHb3a8ZPWv0gbhkDAia/ta-lib-0.4.0-src.tar.gz?dl=0" -O /tmp/ta-lib-0.4.0-src.tar.gz
RUN tar zxvf /tmp/ta-lib-0.4.0-src.tar.gz -C /tmp
RUN cd /tmp/ta-lib; ./configure --prefix=/usr; make; make install
RUN cd /; rm -rf /tmp/ta-lib /tmp/ta-lib-0.4.0-src.tar.gz

RUN pip install cython urllib3==1.24.3 APScheduler==3.6.1 argcomplete==2.0.0 coinbase==2.0.6 configparser==3.5.0 Babel==2.9.1 CurrencyConverter==0.16.1 Flask==2.2.5 Flask-Login==0.6.2 docker==5.0.3 lib==3.0.0 pyOpenSSL==22.0.0 mysqlclient==2.1.0 oauth==1.0.1 pandas==1.1.5 numpy==1.25.0 Pillow>=6.2.2 plotly==5.15.0 python_resize_image==1.1.11 PyVirtualDisplay==1.3.2 redis==4.4.4 requests==2.31.0 scipy==1.11.1 selenium==3.8.1 setproctitle==1.1.10 simplejson==3.13.2
RUN pip install ta-lib==0.4.14 str2bool==1.1 openpyxl==2.6.3 xlrd==1.2.0 requests-unixsocket==0.2.0 pylint==2.4.4 waitress six==1.12 systemd==0.16.1 tzlocal==2.1b1 cryptocompare==0.7.3 pandas_ta==0.2.23b0 pyyaml==5.4.1 gitpython werkzeug==2.2.3 click>=8.1.3 rq==1.15.0 websocket-client==1.5.1 pytest==6.0.1 backports.shutil-get-terminal-size==1.0.0 scandir==1.10.0 browsepy==0.5.6 pip==9.0.1
CMD ["python"]
