FROM jenkins/jnlp-slave:latest

USER root

ENV AWS_ACCESS_KEY_ID ****************
ENV AWS_SECRET_ACCESS_KEY ***************
ENV AWS_DEFAULT_REGION ***********
ENV AWS_DEFAULT_OUTPUT ************

RUN apt-get update
RUN apt-get install vim nano expect sshpass curl apt-transport-https -y

RUN apt install python3.7 -y
RUN apt-get update \
  && apt-get install -y python3-pip python3-dev \
  && cd /usr/local/bin \
  && ln -s /usr/bin/python3 python \
  && pip3 install --upgrade pip

RUN apt-get install -y libcurl4-gnutls-dev librtmp-dev
RUN apt-get install -y docker.io netcat ntpdate default-mysql-client screen atop jq iotop ntp awscli vim
RUN apt-get install -y make build-essential libssl-dev zlib1g-dev sudo
RUN apt-get install -y wget make git default-libmysqlclient-dev python3-dev xvfb iceweasel redis-tools cron bsdmainutils libssl-dev gcc libsystemd-dev libjpeg-dev zlib1g-dev wget

RUN mkdir -p /usr/lib/docker/cli-plugins
RUN curl -sSL https://github.com/docker/compose/releases/download/v2.9.0/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
RUN chmod +x /usr/local/bin/docker-compose

RUN wget "https://www.dropbox.com/sh/l22jyonei087h4o/AAChfqr_j4ydTDjILz0Q62Y2a/configstore-2.5.0-linux-amd64.tar.gz?dl=0" -O /tmp/configstore-2.5.0-linux-amd64.tar.gz
RUN tar zxvf /tmp/configstore-2.5.0-linux-amd64.tar.gz -C /usr/local/bin
RUN rm -rf /tmp/configstore-2.5.0-linux-amd64.tar.gz
RUN wget "https://www.dropbox.com/sh/l22jyonei087h4o/AAAVa_B_sDXtWZu17RzazsA2a/geckodriver-v0.26.0-linux64.tar.gz?dl=0" -O /tmp/geckodriver-v0.26.0-linux64.tar.gz
RUN tar zxvf /tmp/geckodriver-v0.26.0-linux64.tar.gz -C /usr/local/bin
RUN rm -rf /tmp/geckodriver-v0.26.0-linux64.tar.gz
RUN wget "https://www.dropbox.com/sh/l22jyonei087h4o/AABz_MIHb3a8ZPWv0gbhkDAia/ta-lib-0.4.0-src.tar.gz?dl=0" -O /tmp/ta-lib-0.4.0-src.tar.gz
RUN tar zxvf /tmp/ta-lib-0.4.0-src.tar.gz -C /tmp
RUN cd /tmp/ta-lib; /tmp/ta-lib/configure --prefix=/usr &&  make && make install; cd - && rm -rf /tmp/ta-lib
RUN pip install numpy==1.16.0 setuptools-rust setuptools==45.1.0 pip==9.0.1 ccxt==1.50.10 pytest==6.0.1 redis-dump-load gitpython Werkzeug==2.2.2 Flask==2.2.0
RUN echo "jenkins ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
RUN git clone https://github.com/adiabuk/greencandle.git ~jenkins/greencandle && ln -s ~jenkins/greencandle /srv/greencandle
RUN pip install Werkzeug==2.2.2 -e git+https://github.com/adiabuk/binance.git@0.32#egg=binance
RUN cd /srv/greencandle; python setup.py install
RUN rm -rf /srv/greencandle ~jenkins/greencandle
