FROM amrox/python:3.7.0-new
LABEL branch=${BRANCH}
LABEL commit=${COMMIT}
LABEL date=${DATE}

ADD . /srv/greencandle
RUN bash /srv/greencandle/install/bootstrap_docker.sh && \
    cp /srv/greencandle/install/docker-entrypoint*.sh / && \
    cp -rv /srv/greencandle/config /opt/config && \
    chmod +x /docker-entrypoint*.sh

ARG BRANCH="master"
ARG COMMIT=""
ARG DATE=""

# Now set it as an env var
ENV COMMIT_SHA=${COMMIT}
ENV VERSION=${BRANCH}
ENV BUILD_DATE=${DATE}

CMD ["/docker-entrypoint.sh"]
