FROM amrox/mariadb:10.8-new

LABEL branch=${BRANCH}
LABEL commit=${COMMIT}
LABEL date=${DATE}

RUN mkdir /opt/output
COPY install/docker-entrypoint-mysql.sh /docker-entrypoint.sh
COPY config /opt/config
RUN chmod +x /docker-entrypoint.sh

ARG BRANCH="master"
ARG COMMIT=""
ARG DATE=""

ENV MYSQL_PASSWORD=password
ENV MYSQL_DATABASE=greencandle

ENV COMMIT_SHA=${COMMIT}
ENV VERSION=${BRANCH}
ENV BUILD_DATE=${DATE}



