FROM amrox/mariadb:10.1.24


RUN apt-get update \
   && apt-get install -y cron bash wget nginx-extras netcat vim
RUN [ ! -f /usr/local/bin/configstore ] && \
    wget "https://www.dropbox.com/sh/l22jyonei087h4o/AAChfqr_j4ydTDjILz0Q62Y2a/configstore-2.5.0-linux-amd64.tar.gz?dl=0" \
    -O /tmp/configstore-2.5.0-linux-amd64.tar.gz && \
    tar zxvf /tmp/configstore-2.5.0-linux-amd64.tar.gz -C /usr/local/bin && \
    rm -rf /tmp/configstore-2.5.0-linux-amd64.tar.gz
