networks:
  my_net:
    external: true

services:
  dev-fe-cron:
    container_name: dev-fe-cron
    hostname: dev-fe-cron
    logging:
      driver: syslog
      options:
        syslog-facility: local1
    environment:
      - CONFIG_ENV=dev
      - DB=true
    image: amrox/greencandle:${TAG}
    mem_limit: 1G
    restart: always
    entrypoint: /docker-entrypoint.sh "touch /var/log/cron.log && cron && tail -f /var/log/cron.log"
    links:
      - dev-base-mysql:mysql
      - dev-base-redis:redis
    depends_on:
      - dev-base-mysql
      - dev-base-redis
    healthcheck:
      test: ls || exit 1
      interval: 5m
      timeout: 10s
      retries: 5
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws

  dev-be-manual:
    container_name: dev-be-manual
    environment:
      - CONFIG_ENV=dev
      - DB=true
    hostname: dev-be-manual
    working_dir: /data/scripts
    image: amrox/greencandle:${TAG}
    restart: always
    logging:
      driver: syslog
      options:
        syslog-facility: local1
    entrypoint: /docker-entrypoint.sh "tail -f /dev/null"
    links:
      - dev-base-mysql:mysql
      - dev-base-redis:redis
      - dev-be-stream_15m:stream
    depends_on:
      - dev-base-mysql
      - dev-base-redis
    healthcheck:
      test: ls || exit 1
      interval: 5m
      timeout: 10s
      retries: 5
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws

  dev-base-redis:
    container_name: dev-base-redis
    hostname: dev-base-redis
    image: amrox/gc-redis:${TAG}
    ports:
      - 6382:6379
    environment:
      - CONFIG_ENV=dev
    restart: always
    logging:
      driver: syslog
      options:
        syslog-facility: local1
    links:
      - dev-base-mysql:mysql
    entrypoint: /docker-entrypoint.sh redis-server /etc/redis.conf
    healthcheck:
      test: redis-cli ping
      interval: 5m
      timeout: 10s
      retries: 5

  dev-base-mysql:
    container_name: dev-base-mysql
    hostname: dev-base-mysql
    image: amrox/gc-mysql:${TAG}
    ports:
      - 3309:3306
    entrypoint: /docker-entrypoint.sh mysqld
    logging:
      driver: syslog
      options:
        syslog-facility: local1
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - CONFIG_ENV=dev
      - DB=true
    restart: always
    healthcheck:
      test: echo 'SELECT version();'| mysql -uroot -ppassword
      interval: 5m
      timeout: 10s
      retries: 5

  dev-be-stream_15m:
    container_name: dev-be-stream_15m
    hostname: dev-be-stream_15m
    image: amrox/greencandle:${TAG}
    mem_limit: 200M
    networks:
      - my_net
    pull_policy: always
    restart: always
    logging:
      driver: syslog
      options:
        syslog-facility: local1
    entrypoint: /docker-entrypoint.sh stream_data
    links:
      - dev-base-mysql:mysql
      - dev-base-redis:redis
    depends_on:
      - dev-base-mysql
      - dev-base-redis
    environment:
      - CONFIG_ENV=dev
      - DB=true
    healthcheck:
      test: echo || exit 1
      start_period: 5m
      interval: 5m
      timeout: 10s
      retries: 5
    ports:
      - 80:5000
    volumes:
      - /mnt:/mnt
      - /data:/data
      - /var/local:/var/local
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run/:/var/run

  dev-fe-api-filesystem:
    container_name: dev-fe-api-filesystem
    hostname: dev-fe-api-filesystem
    environment:
      - CONFIG_ENV=dev
      - SECRET_KEY=$SECRET_KEY
    logging:
      driver: syslog
      options:
        syslog-facility: local1
    image: amrox/greencandle:${TAG}
    mem_limit: 200M
    pull_policy: always
    restart: always
    entrypoint: /docker-entrypoint.sh filesystem_api
    healthcheck:
      test: curl -Isf http://127.1:6000
      interval: 5m
      timeout: 10s
      retries: 5
    ports:
      - 6000
    volumes:
      - /data:/data
      - /dev/log:/dev/log
      - /root/.aws:/root/.aws
      - /var/run:/var/run

  dev-fe-api-proxy:
    container_name: dev-fe-api-proxy
    hostname: dev-fe-api-proxy
    environment:
      - CONFIG_ENV=dev
      - SECRET_KEY=$SECRET_KEY
    logging:
      driver: syslog
      options:
        syslog-facility: local1
    image: amrox/greencandle:${TAG}
    mem_limit: 200M
    pull_policy: always
    restart: always
    entrypoint: /docker-entrypoint.sh api_proxy
    healthcheck:
      test: curl -qsf http://127.1:5000 >/dev/null
      interval: 5m
      timeout: 10s
      retries: 5
    links:
      - dev-be-api-router:router
      - dev-fe-api-filesystem:filesystem
    ports:
      - 5000
    depends_on:
      - dev-base-mysql
      - dev-base-redis
    volumes:
      - /data:/data
      - /dev/log:/dev/log
      - /root/.aws:/root/.aws
      - /var/run:/var/run
      - /root/.bash_history:/root/.bash_history

  dev-fe-api-dashboard:
    container_name: dev-fe-api-dashboard
    hostname: dev-fe-api-dashboard
    environment:
      - CONFIG_ENV=dev
      - DB=true
      - SECRET_KEY=$SECRET_KEY
    logging:
      driver: syslog
      options:
        syslog-facility: local1
    image: amrox/greencandle:${TAG}
    mem_limit: 600M
    pull_policy: always
    restart: always
    entrypoint: /docker-entrypoint.sh api_dashboard
    links:
      - dev-base-mysql:mysql
      - dev-base-redis:redis
      - dev-be-api-router:router
      - dev-fe-api-filesystem:filesystem
      - dev-fe-api-proxy:proxy
    ports:
      - 5000
    depends_on:
      - dev-base-mysql
      - dev-base-redis
    healthcheck:
      test: curl -Isf http://127.1:5000/dash/healthcheck
      interval: 5m
      timeout: 10s
      retries: 5
    volumes:
      - /data:/data
      - /dev/log:/dev/log
      - /root/.aws:/root/.aws
      - /var/run:/var/run
      - /root/.bash_history:/root/.bash_history

  dev-be-analyse-15m-short1:
    container_name: dev-be-analyse-15m-short1
    hostname: dev-be-analyse-15m-short1
    image: amrox/greencandle:${TAG}
    mem_limit: 500M
    pull_policy: always
    restart: always
    entrypoint: /docker-entrypoint.sh "analyse_data"
    logging:
      driver: syslog
      options:
        syslog-facility: local1
    links:
      - dev-be-api-router:router
      - dev-base-mysql:mysql
      - dev-base-redis:redis
    depends_on:
      - dev-base-mysql
      - dev-base-redis
      - dev-be-get_15m
    environment:
      - ALERT=True
      - STORE_IN_DB=True
      - CONFIG_ENV=dev
      - DB=true
    healthcheck:
      test: find /var/local/lock -mmin -2 -name dev-be-analyse-15m-short1 2>&1  | grep . || exit 1
      start_period: 1h
      interval: 5m
      timeout: 10s
      retries: 5
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run/:/var/run

  dev-gen-be-logwatch:
    container_name: dev-gen-be-logwatch
    hostname: dev-gen-be-logwatch
    image: amrox/greencandle:${TAG}
    mem_limit: 200M
    restart: always
    entrypoint: /docker-entrypoint.sh /usr/local/bin/logwatch
    logging:
      driver: syslog
      options:
        syslog-facility: local1
    environment:
      - CONFIG_ENV=dev
      - DB=false
    volumes:
      - /var/log:/var/log
      - /root/.aws:/root/.aws
      - /var/run:/var/run
    healthcheck:
      test: ls /var/log/gc_dev.log
      interval: 5m
      timeout: 10s
      retries: 5

  dev-gen-be-logtailer-api:
    container_name: dev-gen-be-logtailer-api
    hostname: dev-gen-be-logtailer-api
    image: amrox/greencandle:${TAG}
    mem_limit: 300M
    pull_policy: always
    restart: always
    environment:
      - CONFIG_ENV=dev
      - DB=false
      - SECRET_KEY=$SECRET_KEY
    entrypoint: /docker-entrypoint.sh logtailer
    logging:
      driver: syslog
      options:
        syslog-facility: local1
    ports:
      - 2000
    links:
      - dev-base-mysql:mysql
      - dev-base-redis:redis
    healthcheck:
      test: ls ||exit 1
      interval: 5m
      timeout: 10s
      retries: 5
    volumes:
      - /var/log:/var/log
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run:/var/run
      - /root/.bash_history:/root/.bash_history

  dev-be-get_15m:
    container_name: dev-be-get_15m
    hostname: dev-be-get_15m
    image: amrox/greencandle:${TAG}
    mem_limit: 1000m
    pull_policy: always
    restart: always
    entrypoint: /docker-entrypoint.sh api_data
    networks:
      - my_net
    logging:
      driver: syslog
      options:
        syslog-facility: local1
    links:
      - dev-base-mysql:mysql
      - dev-base-redis:redis
      - dev-be-stream_15m:stream
    depends_on:
      - dev-base-mysql
      - dev-base-redis
    environment:
      - CONFIG_ENV=dev
      - DB=true
    healthcheck:
      test: find /var/local/lock/gc_get_15m.lock  -mmin -2 ||exit 1
      interval: 5m
      timeout: 10s
      retries: 5
    volumes:
      - /data:/data
      - /var/local:/var/local
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run/:/var/run

  dev-be-api-router:
    container_name: dev-be-api-router
    hostname: dev-be-api-router
    extra_hosts:
      - "alert:10.0.0.212"
    image: amrox/greencandle:${TAG}
    mem_limit: 200M
    pull_policy: always
    restart: always
    logging:
      driver: syslog
      options:
        syslog-facility: local1
    healthcheck:
      test: curl -Isf http://127.1:1080/healthcheck
      interval: 5m
      timeout: 5s
      retries: 5
    environment:
      - CONFIG_ENV=dev
      - DB=true
    ports:
      - 1083:1080
    links:
      - dev-base-mysql:mysql
      - dev-base-redis:redis
    depends_on:
      - dev-base-mysql
      - dev-base-redis
    entrypoint: /docker-entrypoint.sh api_router
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws
      - /var/run:/var/run
      - /var/local:/var/local
      - /root/.bash_history:/root/.bash_history
