FROM amrox/mariadb:10.8-new

RUN mkdir /opt/output
COPY install/docker-entrypoint-mysql.sh /docker-entrypoint.sh
COPY config /opt/config
RUN chmod +x /docker-entrypoint.sh

ENV MYSQL_PASSWORD=password
ENV MYSQL_DATABASE=greencandle

ARG BRANCH
ARG COMMIT
ARG DATE
ENV COMMIT_SHA=$COMMIT
ENV VERSION=$BRANCH
ENV BUILD_DATE=$DATE

ENTRYPOINT ["docker-entrypoint.sh"]

EXPOSE 3306
CMD ["mariadbd"]


