FROM amrox/python:3.7.0
LABEL branch=${BRANCH}
LABEL commit=${COMMIT}
LABEL date=${DATE}

ADD . /srv/greencandle
RUN bash /srv/greencandle/install/bootstrap_docker.sh && \
    cp /srv/greencandle/install/docker-entrypoint.sh / && \
    cp /srv/greencandle/install/docker-entrypoint-api.sh / && \
    cp /srv/greencandle/install/docker-entrypoint-test.sh / && \
    cp -rv /srv/greencandle/config /opt/config && \
    chmod +x /docker-entrypoint*.sh

RUN apt-get update \
   && apt-get install -y vim && \
   apt-get -y clean && apt-get -y autoclean && apt-get -y autoremove

ARG BRANCH="master"
ARG COMMIT=""
ARG DATE=""

# Now set it as an env var
ENV COMMIT_SHA=${COMMIT}
ENV VERSION=${BRANCH}
ENV BUILD_DATE=${DATE}

CMD ["/docker-entrypoint.sh"]
