version: "3.1"
services:

  fe-cadvisor:
    container_name: fe-cadvisor
    hostname: fe-cadvisor
    image: gcr.io/google_containers/cadvisor:v0.35.0
    restart: on-failure
    volumes:
      - /:/rootfs
      - /var/run:/var/run
      - /sys:/sys
      - /var/lib/docker:/var/lib/docker
      - /dev/disk:/dev/disk
    healthcheck:
      test: "printf 'GET /healthz HTTP/1.1\r\nHost: localhost\r\n\r\n' | nc localhost 8080"
      interval: 1m
      timeout: 2s
      retries: 5

  base-redis:
    container_name: base-redis
    hostname: base-redis
    image: amrox/gc-redis:${TAG}
    restart: on-failure
    links:
      - base-mysql:mysql
    ports:
      - 6379:6379
    healthcheck:
      test: redis-cli ping
      interval: 1m
      timeout: 2s
      retries: 5

  base-mysql:
    container_name: base-mysql
    hostname: base-mysql
    image: amrox/gc-mysql:${TAG}
    entrypoint: /docker-entrypoint.sh mysqld
    environment:
      - CONFIG_ENV=stag
      - MYSQL_ROOT_PASSWORD=password
    restart: on-failure
    ports:
      - 3306:3306
    healthcheck:
      test: echo 'SELECT version();'| mysql -uroot -ppassword
      interval: 1m
      timeout: 2s
      retries: 5

  fe-api:
    container_name: fe-api
    hostname: fe-api
    environment:
      - CONFIG_ENV=stag/cron
      - HOST=$HOSTNAME
    logging:
      driver: journald
    image: amrox/greencandle:${TAG}
    restart: on-failure
    entrypoint: /docker-entrypoint-api.sh api --test
    links:
      - base-mysql:mysql
      - base-redis:redis
    ports:
      - 5000
    depends_on:
      - base-mysql
      - base-redis
    healthcheck:
      test: find /var/run/  -mmin -2 -name api 2>&1 |grep -q api || exit 1
      interval: 1m
      timeout: 2s
      retries: 5
    volumes:
      - /data:/data
      - /dev/log:/dev/log
      - /var/run/systemd/journal/socket:/var/run/systemd/journal/socket

  fe-cron:
    container_name: fe-cron
    hostname: fe-cron
    environment:
      - CONFIG_ENV=stag/cron
      - HOST=$HOSTNAME
    image: amrox/greencandle:${TAG}
    entrypoint: /docker-entrypoint.sh cron -f
    logging:
      driver: journald
    links:
      - base-mysql:mysql
      - base-redis:redis
    depends_on:
      - base-mysql
      - base-redis
    healthcheck:
      test: find /var/run/  -mmin -2 -name cron 2>&1 |grep -q cron ||exit 1
      interval: 1m
      timeout: 2s
      retries: 5
    volumes:
      - /data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/log:/dev/log
      - /var/run/systemd/journal/socket:/var/run/systemd/journal/socket

  fe-webserver:
     container_name: fe-webserver
     hostname: fe-webserver
     image: amrox/webserver:${TAG}
     healthcheck:
       test: service nginx status || exit 1
       interval: 5m
       timeout: 5s
       retries: 5
     environment:
       - CONFIG_ENV=stag
       - HOST=$HOSTNAME
     ports:
       - 8888:8888
     links:
       - fe-dashboard:dashboard
       - fe-cadvisor:cadvisor
       - fe-api:api
       - base-mysql:mysql
       - base-redis:redis
     depends_on:
       - fe-dashboard
       - fe-cadvisor
       - fe-api
       - base-mysql
       - base-redis
     entrypoint: /docker-entrypoint.sh nginx -g 'daemon off;'
     volumes:
       - /data:/data

  fe-dashboard:
    container_name: fe-dashboard
    hostname: fe-dashboard
    image: amrox/dashboard:${TAG}
    ports:
      - 8080:3030
    healthcheck:
      test: curl  --fail 127.1:3030/dashboard/gc || exit 1
      interval: 10m
      timeout: 5s
      retries: 5
    entrypoint: /run.sh
    links:
      - base-mysql:mysql
    depends_on:
      - base-mysql

  be-2ma-eth-4h:
    container_name : be-2ma-eth-4h
    hostname: be-2ma-eth-4h
    image: amrox/greencandle:${TAG}
    entrypoint: /docker-entrypoint.sh backend --test
    logging:
      driver: journald
    links:
      - base-mysql:mysql
      - base-redis:redis
    depends_on:
      - base-mysql
      - base-redis
    environment:
      - CONFIG_ENV=stag/2MA/ETH
      - HOST=$HOSTNAME
    healthcheck:
      test: find /var/run/  -mmin -2 -name greencandle 2>&1 |grep -q greencandle ||exit 1
      interval: 1m
      timeout: 2s
      retries: 5
    volumes:
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run/systemd/journal/socket:/var/run/systemd/journal/socket

  be-2ma-usdt-4h:
    container_name: be-2ma-usdt-4h
    hostname: be-2ma-usdt-4h
    image: amrox/greencandle:${TAG}
    entrypoint: /docker-entrypoint.sh backend --test
    logging:
      driver: journald
    links:
      - base-mysql:mysql
      - base-redis:redis
    depends_on:
      - base-mysql
      - base-redis
    environment:
      - CONFIG_ENV=stag/2MA/USDT
      - HOST=$HOSTNAME
    healthcheck:
      test: find /var/run/  -mmin -2 -name greencandle 2>&1 |grep -q greencandle ||exit 1
      interval: 1m
      timeout: 2s
      retries: 5
    volumes:
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run/systemd/journal/socket:/var/run/systemd/journal/socket

  be-2ma-btc-4h:
    container_name: be-2ma-btc-5h
    hostname: be-2ma-btc-4h
    image: amrox/greencandle:${TAG}
    entrypoint: /docker-entrypoint.sh backend --test
    logging:
      driver: journald
    links:
      - base-mysql:mysql
      - base-redis:redis
    depends_on:
      - base-mysql
      - base-redis
    environment:
      - CONFIG_ENV=stag/2MA/BTC
      - HOST=$HOSTNAME
    healthcheck:
      test: find /var/run/  -mmin -2 -name greencandle 2>&1 |grep -q greencandle ||exit 1
      interval: 1m
      timeout: 2s
      retries: 5
    volumes:
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run/systemd/journal/socket:/var/run/systemd/journal/socket

  be-2ma-bnb-4h:
    container_name: be-2ma-bnb-4h
    hostname: stag2ma-bnb-4h
    image: amrox/greencandle:${TAG}
    entrypoint: /docker-entrypoint.sh backend --test
    logging:
      driver: journald
    links:
      - base-mysql:mysql
      - base-redis:redis
    depends_on:
      - base-mysql
      - base-redis
    environment:
      - CONFIG_ENV=stag/2MA/BNB
      - HOST=$HOSTNAME
    healthcheck:
      test: find /var/run/  -mmin -2 -name greencandle 2>&1 |grep -q greencandle ||exit 1
      interval: 1m
      timeout: 2s
      retries: 5
    volumes:
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run/systemd/journal/socket:/var/run/systemd/journal/socket

  be-4ma-usdt-4h:
    container_name: be-4ma-usdt-4h
    hostname: be-4ma-usdt-4h
    image: amrox/greencandle:${TAG}
    entrypoint: /docker-entrypoint.sh backend --test
    logging:
      driver: journald
    links:
      - base-mysql:mysql
      - base-redis:redis
    depends_on:
      - base-mysql
      - base-redis
    environment:
      - CONFIG_ENV=stag/4MA/USDT
      - HOST=$HOSTNAME
    healthcheck:
      test: find /var/run/  -mmin -2 -name greencandle 2>&1 |grep -q greencandle ||exit 1
      interval: 1m
      timeout: 2s
      retries: 5
    volumes:
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run/systemd/journal/socket:/var/run/systemd/journal/socket

  be-4ma-eth-4h:
    container_name: be-4ma-eth-4h
    hostname: be-4ma-eth-4h
    image: amrox/greencandle:${TAG}
    entrypoint: /docker-entrypoint.sh backend --test
    logging:
      driver: journald
    links:
      - base-mysql:mysql
      - base-redis:redis
    depends_on:
      - base-mysql
      - base-redis
    environment:
      - CONFIG_ENV=stag/4MA/ETH
      - HOST=$HOSTNAME
    healthcheck:
      test: find /var/run/  -mmin -2 -name greencandle 2>&1 |grep -q greencandle ||exit 1
      interval: 1m
      timeout: 2s
      retries: 5
    volumes:
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run/systemd/journal/socket:/var/run/systemd/journal/socket

  be-4ma-btc-4h:
    container_name: be-4ma-btc-4h
    hostname: be-4ma-btc-4h
    image: amrox/greencandle:${TAG}
    entrypoint: /docker-entrypoint.sh backend --test
    logging:
      driver: journald
    links:
      - base-mysql:mysql
      - base-redis:redis
    depends_on:
      - base-mysql
      - base-redis
    environment:
      - CONFIG_ENV=stag/4MA/BTC
      - HOST=$HOSTNAME
    healthcheck:
      test: find /var/run/  -mmin -2 -name greencandle 2>&1 |grep -q greencandle ||exit 1
      interval: 1m
      timeout: 2s
      retries: 5
    volumes:
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run/systemd/journal/socket:/var/run/systemd/journal/socket

  be-4ma-bnb-4h:
    container_name: be-4ma-bnb-4h
    hostname: be-4ma-bnb-4h
    image: amrox/greencandle:${TAG}
    entrypoint: /docker-entrypoint.sh backend --test
    logging:
      driver: journald
    links:
      - base-mysql:mysql
      - base-redis:redis
    depends_on:
      - base-mysql
      - base-redis
    environment:
      - CONFIG_ENV=stag/4MA/BNB
      - HOST=$HOSTNAME
    healthcheck:
      test: find /var/run/  -mmin -2 -name greencandle 2>&1 |grep -q greencandle ||exit 1
      interval: 1m
      timeout: 2s
      retries: 5
    volumes:
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run/systemd/journal/socket:/var/run/systemd/journal/socket

  be-5ma-btc-4h:
    container_name: be-5ma-btc-4h
    hostname: be-5ma-btc-4h
    image: amrox/greencandle:${TAG}
    entrypoint: /docker-entrypoint.sh backend --test
    logging:
      driver: journald
    links:
      - base-mysql:mysql
      - base-redis:redis
    depends_on:
      - base-mysql
      - base-redis
    environment:
      - CONFIG_ENV=stag/5MA/BTC
      - HOST=$HOSTNAME
    healthcheck:
      test: find /var/run/  -mmin -2 -name greencandle 2>&1 |grep -q greencandle ||exit 1
      interval: 1m
      timeout: 2s
      retries: 5
    volumes:
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run/systemd/journal/socket:/var/run/systemd/journal/socket

  be-5ma-eth-4h:
    container_name: be-5ma-eth-4h
    hostname: be-5ma-eth-4h
    image: amrox/greencandle:${TAG}
    entrypoint: /docker-entrypoint.sh backend --test
    logging:
      driver: journald
    links:
      - base-mysql:mysql
      - base-redis:redis
    depends_on:
      - base-mysql
      - base-redis
    environment:
      - CONFIG_ENV=stag/5MA/ETH
      - HOST=$HOSTNAME
    healthcheck:
      test: find /var/run/  -mmin -2 -name greencandle 2>&1 |grep -q greencandle ||exit 1
      interval: 1m
      timeout: 2s
      retries: 5
    volumes:
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run/systemd/journal/socket:/var/run/systemd/journal/socket

  be-5ma-usdt-4h:
    container_name: be-5ma-usdt-4h
    hostname: be-5ma-usdt-4h
    image: amrox/greencandle:${TAG}
    entrypoint: /docker-entrypoint.sh backend --test
    logging:
      driver: journald
    links:
      - base-mysql:mysql
      - base-redis:redis
    depends_on:
      - base-mysql
      - base-redis
    environment:
      - CONFIG_ENV=stag/5MA/USDT
      - HOST=$HOSTNAME
    healthcheck:
      test: find /var/run/  -mmin -2 -name greencandle 2>&1 |grep -q greencandle ||exit 1
      interval: 1m
      timeout: 2s
      retries: 5
    volumes:
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run/systemd/journal/socket:/var/run/systemd/journal/socket
