FROM amrox/nginx:stable

RUN apt-get update \
   && apt-get install -y cron bash wget nginx-extras netcat vim && \
   apt-get purge -y guile-2.2-libs libpython2.7-minimal exim4-daemon-light && \
   apt-get -y clean && apt-get -y autoclean && apt-get -y autoremove
RUN [ ! -f /usr/local/bin/configstore ] && \
    wget "http://local.amrox.loc/files/configstore-2.5.0-linux-amd64.tar.gz" \
    -O /tmp/configstore-2.5.0-linux-amd64.tar.gz && \
    tar zxvf /tmp/configstore-2.5.0-linux-amd64.tar.gz -C /usr/local/bin && \
    rm -rf /tmp/configstore-2.5.0-linux-amd64.tar.gz
RUN apt-get -y clean && apt-get -y autoclean && apt-get -y autoremove
