FROM python:3.13.2

RUN install -m 0755 -d /etc/apt/keyrings && \
curl -sS https://download.docker.com/linux/debian/gpg | gpg --dearmor > /usr/share/keyrings/docker-ce.gpg && \
chmod a+r /usr/share/keyrings/docker-ce.gpg && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-ce.gpg] https://download.docker.com/linux/debian buster stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
RUN apt-get update && \
    apt-get -y install screen vim cron netcat-openbsd default-mysql-client bsdmainutils libssl-dev libsystemd-dev xvfb xauth firefox-esr sudo docker-ce-cli docker-compose-plugin --no-install-recommends && \
    wget "http://local.amrox.loc/files/geckodriver-v0.26.0-linux64.tar.gz" -O /tmp/geckodriver-v0.26.0-linux64.tar.gz && \
    tar zxvf /tmp/geckodriver-v0.26.0-linux64.tar.gz -C /usr/local/bin && \
    rm -rf /tmp/geckodriver-v0.26.0-linux64.tar.gz  && \
    wget "http://local.amrox.loc/files/configstore-2.5.0-linux-amd64.tar.gz" -O /tmp/configstore-2.5.0-linux-amd64.tar.gz && \
    tar zxvf /tmp/configstore-2.5.0-linux-amd64.tar.gz -C /usr/local/bin && \
    rm -rf /tmp/configstore-2.5.0-linux-amd64.tar.gz && \
    wget "http://local.amrox.loc/files/ta-lib-0.4.0-src.tar.gz" -O /tmp/ta-lib-0.4.0-src.tar.gz && \
    tar zxvf /tmp/ta-lib-0.4.0-src.tar.gz -C /tmp && \
    cd /tmp/ta-lib; ./configure --prefix=/usr; make; make install && \
    git clone https://github.com/adiabuk/greencandle.git /tmp/greencandle && \
    pip install -r /tmp/greencandle/requirements.txt && \
    wget http://local.amrox.loc/files/talib.tgz -O /tmp/talib.tgz && \
    tar zxvf /tmp/talib.tgz -C /tmp && \
    cd /tmp/TA-Lib-ta-lib-python-5974b7f/ && python setup.py install && \
    apt purge -y gcc g++-8 libx265-165 mercurial-common && apt -y autoremove && apt autoclean && \
    apt-get clean; apt-get autoclean; rm -rf /var/lib/apt/lists/* && \
    mkdir -p /opt/output && cd / && rm -rf /tmp/*


CMD ["python"]
