services:
  stag-gen-be-logwatch:
    container_name: stag-gen-be-logwatch
    hostname: stag-gen-be-logwatch
    image: amrox/greencandle:${TAG}
    mem_limit: 200m
    restart: always
    entrypoint: /docker-entrypoint.sh /usr/local/bin/logwatch
    environment:
      - CONFIG_ENV=stag/fe/cron
      - DB=false
    volumes:
      - /var/log:/var/log
      - /root/.aws:/root/.aws
      - /var/run:/var/run
    healthcheck:
      test: ls /var/log/gc_stag.log
      interval: 5m
      timeout: 10s
      retries: 5

  stag-gen-be-logtailer-api:
    container_name: stag-gen-be-logtailer-api
    hostname: stag-gen-be-logtailer-api
    image: amrox/greencandle:${TAG}
    mem_limit: 300m
    pull_policy: always
    restart: always
    environment:
      - CONFIG_ENV=stag
      - DB=false
      - SECRET_KEY=$SECRET_KEY
    entrypoint: /docker-entrypoint.sh logtailer
    logging:
      driver: syslog
      options:
        syslog-facility: local5
    ports:
      - 2000
    links:
      - stag-base-mysql:mysql
      - stag-base-redis:redis
    healthcheck:
      test: ls ||exit 1
      interval: 5m
      timeout: 10s
      retries: 5
    volumes:
      - /var/log:/var/log
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run:/var/run
      - /root/.bash_history:/root/.bash_history

  stag-base-redis:
    container_name: stag-base-redis
    hostname: stag-base-redis
    image: amrox/gc-redis:${TAG}
    mem_limit: 300m
    pull_policy: always
    restart: always
    links:
      - stag-base-mysql:mysql
    ports:
      - 6381:6379
    healthcheck:
      test: redis-cli ping
      interval: 5m
      timeout: 10s
      retries: 5
    volumes:
      - /var/run:/var/run
      - /root/.aws:/root/.aws
      - /root/.bash_history:/root/.bash_history

  stag-base-mysql:
    container_name: stag-base-mysql
    hostname: stag-base-mysql
    image: amrox/gc-mysql:${TAG}
    mem_limit: 300m
    pull_policy: always
    entrypoint: /docker-entrypoint.sh "--max-connections=5000"
    environment:
      - CONFIG_ENV=stag
      - MYSQL_ROOT_PASSWORD=password
      - DB=true
    restart: always
    ports:
      - 3308:3306
    healthcheck:
      test: echo 'SELECT version();'| mysql -uroot -ppassword
      interval: 5m
      timeout: 10s
      retries: 5
    volumes:
      - /var/run/systemd/journal/socket:/var/run/systemd/journal/socket
      - /root/.aws:/root/.aws
      - /root/.bash_history:/root/.bash_history

  stag-fe-api-dashboard:
    container_name: stag-fe-api-dashboard
    hostname: stag-fe-api-dashboard
    environment:
      - CONFIG_ENV=stag/fe/api
      - DB=true
      - SECRET_KEY=$SECRET_KEY
    logging:
      driver: syslog
      options:
        syslog-facility: local5
    image: amrox/greencandle:${TAG}
    mem_limit: 600m
    pull_policy: always
    restart: always
    entrypoint: /docker-entrypoint.sh api_dashboard
    links:
      - stag-base-mysql:mysql
      - stag-base-redis:redis
      - stag-be-api-router:router
      - stag-fe-api-filesystem:filesystem
      - stag-fe-api-proxy:proxy
    ports:
      - 5000
    depends_on:
      - stag-base-mysql
      - stag-base-redis
    healthcheck:
      test: curl -Isf http://127.1:5000/dash/healthcheck
      interval: 5m
      timeout: 10s
      retries: 5
    volumes:
      - /data:/data
      - /dev/log:/dev/log
      - /root/.aws:/root/.aws
      - /var/run:/var/run
      - /root/.bash_history:/root/.bash_history

  stag-be-manual:
    container_name: stag-be-manual
    hostname: stag-be-manual
    working_dir: /data/scripts
    environment:
      - CONFIG_ENV=stag/be/manual
      - DB=true
    image: amrox/greencandle:${TAG}
    mem_limit: 500m
    pull_policy: always
    restart: always
    entrypoint: /docker-entrypoint.sh "tail -f /dev/null"
    logging:
      driver: syslog
      options:
        syslog-facility: local5
    links:
      - stag-base-mysql:mysql
      - stag-base-redis:redis
      - stag-be-api-router:router
    depends_on:
      - stag-base-mysql
      - stag-base-redis
    healthcheck:
      test: ls || exit 1
      interval: 5m
      timeout: 10s
      retries: 5
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run:/var/run
      - /root/.bash_history:/root/.bash_history
      - /root/.bashrc:/root/.bashrc
      - /root/.ipython:/root/.ipython

  stag-fe-cron:
    container_name: stag-fe-cron
    hostname: stag-fe-cron
    environment:
      - CONFIG_ENV=stag/fe/cron
      - DB=true
    image: amrox/greencandle:${TAG}
    mem_limit: 5g
    pull_policy: always
    restart: always
    entrypoint: /docker-entrypoint.sh "cron -f"
    logging:
      driver: syslog
      options:
        syslog-facility: local5
    links:
      - stag-base-mysql:mysql
      - stag-base-redis:redis
    depends_on:
      - stag-base-mysql
      - stag-base-redis
    healthcheck:
      test: find /var/run/  -mmin -2 -name cron 2>&1 |grep -q cron ||exit 1
      interval: 5m
      timeout: 10s
      retries: 5
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.bash_history:/root/.bash_history

  stag-fe-webserver:
    container_name: stag-fe-webserver
    hostname: stag-fe-webserver
    image: amrox/webserver:${TAG}
    mem_limit: 200m
    pull_policy: always
    restart: always
    healthcheck:
      test: curl -Isf 127.1:3333
      interval: 5m
      timeout: 5s
      retries: 5
    environment:
      - CONFIG_ENV=stag
      - DB=false
    ports:
      - 3333:3333
    links:
      - stag-fe-api-dashboard:api_dash
      - stag-base-mysql:mysql
      - stag-base-redis:redis
      - stag-gen-be-logtailer-api:logs
      - stag-fe-api-proxy:proxy
    depends_on:
      - stag-base-mysql
      - stag-base-redis
    entrypoint: /docker-entrypoint.sh "nginx -g 'daemon off;'"
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws
      - /root/.bash_history:/root/.bash_history
      - /var/run:/var/run
      - /var/local:/var/local

  stag-fe-api-proxy:
    container_name: stag-fe-api-proxy
    hostname: stag-fe-api-proxy
    environment:
      - CONFIG_ENV=stag/fe/api
      - SECRET_KEY=$SECRET_KEY
    logging:
      driver: syslog
      options:
        syslog-facility: local5
    image: amrox/greencandle:${TAG}
    mem_limit: 200m
    pull_policy: always
    restart: always
    entrypoint: /docker-entrypoint.sh api_proxy
    healthcheck:
      test: curl -qsf http://127.1:5000 >/dev/null
      interval: 5m
      timeout: 10s
      retries: 5
    links:
      - stag-be-api-router:router
      - stag-fe-api-filesystem:filesystem
    ports:
      - 5000
    depends_on:
      - stag-base-mysql
      - stag-base-redis
    volumes:
      - /data:/data
      - /dev/log:/dev/log
      - /root/.aws:/root/.aws
      - /var/run:/var/run
      - /root/.bash_history:/root/.bash_history

  stag-fe-api-filesystem:
    container_name: stag-fe-api-filesystem
    hostname: stag-fe-api-filesystem
    environment:
      - CONFIG_ENV=stag/fe/api
      - SECRET_KEY=$SECRET_KEY
    logging:
      driver: syslog
      options:
        syslog-facility: local5
    image: amrox/greencandle:${TAG}
    mem_limit: 200m
    pull_policy: always
    restart: always
    entrypoint: /docker-entrypoint.sh filesystem_api
    healthcheck:
      test: curl -Isf http://127.1:6000
      interval: 5m
      timeout: 10s
      retries: 5
    ports:
      - 6000
    volumes:
      - /data:/data
      - /dev/log:/dev/log
      - /root/.aws:/root/.aws
      - /var/run:/var/run

  stag-be-api-router:
    container_name: stag-be-api-router
    hostname: stag-be-api-router
    image: amrox/greencandle:${TAG}
    mem_limit: 200m
    pull_policy: always
    restart: always
    healthcheck:
      test: curl -Isf http://127.1:1080/healthcheck
      interval: 5m
      timeout: 5s
      retries: 5
    environment:
      - CONFIG_ENV=stag
      - DB=true
    ports:
      - 1082:1080
    extra_hosts:
      - "alert:10.0.0.212"
    links:
      - stag-base-mysql:mysql
      - stag-base-redis:redis
      - stag-be-api-any-5m-cross-long:any-5m-long
      - stag-be-api-any-5m-cross-short:any-5m-short
      - stag-be-api-any-1m-cross-long:any-1m-long
      - stag-be-api-any-1m-cross-short:any-1m-short
      - stag-be-api-any2-1m-cross-long:any2-1m-long
      - stag-be-api-any2-1m-cross-short:any2-1m-short
    depends_on:
      - stag-base-mysql
      - stag-base-redis
    entrypoint: /docker-entrypoint.sh api_router --test
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws
      - /var/run:/var/run
      - /var/local:/var/local
      - /root/.bash_history:/root/.bash_history

  stag-be-api-any2-1m-cross-long:
    container_name: stag-be-api-any2-1m-cross-long
    hostname: stag-be-api-any2-1m-cross-long
    image: amrox/greencandle:${TAG}
    mem_limit: 600m
    pull_policy: always
    restart: always
    entrypoint: /docker-entrypoint.sh "backend_api --test api & backend_api --test queue"
    logging:
      driver: syslog
      options:
        syslog-facility: local5
    environment:
      - CONFIG_ENV=stag/be/any2/long/1m
      - intermittent="true"
      - DB=true
    ports:
      - 20000
    links:
      - stag-base-mysql:mysql
      - stag-base-redis:redis
    depends_on:
      - stag-base-mysql
      - stag-base-redis
    healthcheck:
      test: api_healthcheck.sh || bash -c 'kill -s 15 -1 && (sleep 10; kill -s 9 -1)'
      interval: 5m
      timeout: 10s
      retries: 5
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run:/var/run
      - /var/local:/var/local
      - /root/.bash_history:/root/.bash_history

  stag-be-api-any2-1m-cross-short:
    container_name: stag-be-api-any2-1m-cross-short
    hostname: stag-be-api-any2-1m-cross-short
    image: amrox/greencandle:${TAG}
    mem_limit: 600m
    pull_policy: always
    restart: always
    entrypoint: /docker-entrypoint.sh "backend_api --test api & backend_api --test queue"
    logging:
      driver: syslog
      options:
        syslog-facility: local5
    environment:
      - CONFIG_ENV=stag/be/any2/short/1m
      - intermittent="true"
      - DB=true
      - no_proxy=router
    ports:
      - 20000
    links:
      - stag-base-mysql:mysql
      - stag-base-redis:redis
    depends_on:
      - stag-base-mysql
      - stag-base-redis
    healthcheck:
      test: api_healthcheck.sh || bash -c 'kill -s 15 -1 && (sleep 10; kill -s 9 -1)'
      interval: 5m
      timeout: 10s
      retries: 5
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run:/var/run
      - /var/local:/var/local
      - /root/.bash_history:/root/.bash_history


  stag-be-api-any-1m-cross-long:
    container_name: stag-be-api-any-1m-cross-long
    hostname: stag-be-api-any-1m-cross-long
    image: amrox/greencandle:${TAG}
    mem_limit: 600m
    pull_policy: always
    restart: always
    entrypoint: /docker-entrypoint.sh "backend_api --test api & backend_api --test queue"
    logging:
      driver: syslog
      options:
        syslog-facility: local5
    environment:
      - CONFIG_ENV=stag/be/any/long/1m
      - intermittent="true"
      - DB=true
    ports:
      - 20000
    links:
      - stag-base-mysql:mysql
      - stag-base-redis:redis
    depends_on:
      - stag-base-mysql
      - stag-base-redis
    healthcheck:
      test: api_healthcheck.sh || bash -c 'kill -s 15 -1 && (sleep 10; kill -s 9 -1)'
      interval: 5m
      timeout: 10s
      retries: 5
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run:/var/run
      - /var/local:/var/local
      - /root/.bash_history:/root/.bash_history

  stag-be-api-any-1m-cross-short:
    container_name: stag-be-api-any-1m-cross-short
    hostname: stag-be-api-any-1m-cross-short
    image: amrox/greencandle:${TAG}
    mem_limit: 600m
    pull_policy: always
    restart: always
    entrypoint: /docker-entrypoint.sh "backend_api --test api & backend_api --test queue"
    logging:
      driver: syslog
      options:
        syslog-facility: local5
    environment:
      - CONFIG_ENV=stag/be/any/short/1m
      - intermittent="true"
      - DB=true
      - no_proxy=router
    ports:
      - 20000
    links:
      - stag-base-mysql:mysql
      - stag-base-redis:redis
    depends_on:
      - stag-base-mysql
      - stag-base-redis
    healthcheck:
      test: api_healthcheck.sh || bash -c 'kill -s 15 -1 && (sleep 10; kill -s 9 -1)'
      interval: 5m
      timeout: 10s
      retries: 5
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run:/var/run
      - /var/local:/var/local
      - /root/.bash_history:/root/.bash_history

  stag-be-api-any-5m-cross-long:
    container_name: stag-be-api-any-5m-cross-long
    hostname: stag-be-api-any-5m-cross-long
    image: amrox/greencandle:${TAG}
    mem_limit: 600m
    pull_policy: always
    restart: always
    entrypoint: /docker-entrypoint.sh "backend_api --test api & backend_api --test queue"
    logging:
      driver: syslog
      options:
        syslog-facility: local5
    environment:
      - CONFIG_ENV=stag/be/any/long/5m
      - intermittent="true"
      - DB=true
    ports:
      - 20000
    links:
      - stag-base-mysql:mysql
      - stag-base-redis:redis
    depends_on:
      - stag-base-mysql
      - stag-base-redis
    healthcheck:
      test: api_healthcheck.sh || bash -c 'kill -s 15 -1 && (sleep 10; kill -s 9 -1)'
      interval: 5m
      timeout: 10s
      retries: 5
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run:/var/run
      - /var/local:/var/local
      - /root/.bash_history:/root/.bash_history

  stag-be-api-any-5m-cross-short:
    container_name: stag-be-api-any-5m-cross-short
    hostname: stag-be-api-any-5m-cross-short
    image: amrox/greencandle:${TAG}
    mem_limit: 600m
    pull_policy: always
    restart: always
    entrypoint: /docker-entrypoint.sh "backend_api --test api & backend_api --test queue"
    logging:
      driver: syslog
      options:
        syslog-facility: local5
    environment:
      - CONFIG_ENV=stag/be/any/short/5m
      - intermittent="true"
      - DB=true
      - no_proxy=router
    ports:
      - 20000
    links:
      - stag-base-mysql:mysql
      - stag-base-redis:redis
    depends_on:
      - stag-base-mysql
      - stag-base-redis
    healthcheck:
      test: api_healthcheck.sh || bash -c 'kill -s 15 -1 && (sleep 10; kill -s 9 -1)'
      interval: 5m
      timeout: 10s
      retries: 5
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run:/var/run
      - /var/local:/var/local
      - /root/.bash_history:/root/.bash_history
