FROM jenkins/jnlp-slave:latest-jdk11

USER root

ENV AWS_ACCESS_KEY_ID ****************
ENV AWS_SECRET_ACCESS_KEY ***************
ENV AWS_DEFAULT_REGION ***********
ENV AWS_DEFAULT_OUTPUT ************

RUN apt-get update && \
    apt-get install -y vim nano expect sshpass curl apt-transport-https wget \
        libcurl4-gnutls-dev librtmp-dev docker.io netcat ntpdate default-mysql-client screen libbz2-dev \
        atop jq iotop ntp awscli vim make build-essential libssl-dev zlib1g-dev sudo \
        git default-libmysqlclient-dev python3-dev xvfb iceweasel redis-tools cron \
        bsdmainutils libssl-dev gcc libsystemd-dev libjpeg-dev zlib1g-dev libffi-dev libsqlite3-dev liblzma-dev

RUN  wget https://www.python.org/ftp/python/3.9.0/Python-3.9.0.tgz
RUN tar -xf Python-3.9.0.tgz && cd Python-3.9.0 && \
    ./configure --prefix=/usr/local --enable-optimizations --enable-shared LDFLAGS="-Wl,-rpath /usr/local/lib" && \
    make altinstall && cd .. && rm -rf Python-3.9.0.tgz && rm -rf Python-3.9.0 && \
    cd /usr/local/bin && ln -s python3.9 python && ln -s pip3.9 pip

RUN mkdir -p /usr/lib/docker/cli-plugins && \
    curl -sSL https://github.com/docker/compose/releases/download/v2.9.0/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose && \
    chmod +x /usr/local/bin/docker-compose

RUN wget "https://www.dropbox.com/sh/l22jyonei087h4o/AAChfqr_j4ydTDjILz0Q62Y2a/configstore-2.5.0-linux-amd64.tar.gz?dl=0" -O /tmp/configstore-2.5.0-linux-amd64.tar.gz && \
    tar zxvf /tmp/configstore-2.5.0-linux-amd64.tar.gz -C /usr/local/bin && \
    rm -rf /tmp/configstore-2.5.0-linux-amd64.tar.gz && \
    wget "https://www.dropbox.com/sh/l22jyonei087h4o/AAAVa_B_sDXtWZu17RzazsA2a/geckodriver-v0.26.0-linux64.tar.gz?dl=0" -O /tmp/geckodriver-v0.26.0-linux64.tar.gz && \
    tar zxvf /tmp/geckodriver-v0.26.0-linux64.tar.gz -C /usr/local/bin && \
    rm -rf /tmp/geckodriver-v0.26.0-linux64.tar.gz && \
    wget "https://www.dropbox.com/sh/l22jyonei087h4o/AABz_MIHb3a8ZPWv0gbhkDAia/ta-lib-0.4.0-src.tar.gz?dl=0" -O /tmp/ta-lib-0.4.0-src.tar.gz && \
    tar zxvf /tmp/ta-lib-0.4.0-src.tar.gz -C /tmp && \
    cd /tmp/ta-lib; /tmp/ta-lib/configure --prefix=/usr &&  make && make install; cd - && rm -rf /tmp/ta-lib && \
    pip install wheel numpy==1.25.0 setuptools-rust setuptools==45.1.0 pip==9.0.1 pytest==6.0.1 gitpython werkzeug==2.2.3 Flask==2.2.5 importlib-metadata==4.12.0 ccxt send_nsca3==0.1.6.0 && \
    echo "jenkins ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers && \
    git clone https://github.com/adiabuk/greencandle.git -b dev ~jenkins/greencandle && ln -s ~jenkins/greencandle /srv/greencandle && \
    cd /srv/greencandle; python setup.py install && \
    rm -rf /srv/greencandle ~jenkins/greencandle
