version: "3.1"
services:

  be-analyse_data_4h_low-rsi:
    container_name: be-analyse_data_4h_low-rsi
    hostname: be-analyse_data_4h_low-rsi
    image: amrox/greencandle
    entrypoint: /docker-entrypoint-data.sh analyse_data
    logging:
      driver: journald
    links:
      - be-get_data_4h:data
      - base-mysql-local:mysql
      - base-redis-local:redis
    depends_on:
      - base-mysql-local
      - base-redis-local
      - be-get_data_4h
    environment:
      - CONFIG_ENV=test/data/long1
      - HOST=$HOSTNAME
    healthcheck:
      test: find /var/run/  -mmin -2 -name greencandle 2>&1 |grep -q greencandle ||exit 1
      interval: 1m
      timeout: 2s
      retries: 5
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run/systemd/journal/socket:/var/run/systemd/journal/socket

  be-analyse_data_4h_big-change:
    container_name: be-analyse_data_4h_big-change
    hostname: be-analyse_data_4h_big-change
    image: amrox/greencandle
    entrypoint: /docker-entrypoint-data.sh analyse_data
    logging:
      driver: journald
    links:
      - base-mysql-local:mysql
      - base-redis-local:redis
      - be-get_data_4h:data
    depends_on:
      - base-mysql-local
      - base-redis-local
      - be-get_data_4h
    environment:
      - CONFIG_ENV=test/data/long3
      - HOST=$HOSTNAME
    healthcheck:
      test: find /var/run/  -mmin -2 -name greencandle 2>&1 |grep -q greencandle ||exit 1
      interval: 1m
      timeout: 2s
      retries: 5
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run/systemd/journal/socket:/var/run/systemd/journal/socket

  be-analyse_data_4h_very-low-rsi:
    container_name: be-analyse_data_4h_very-low-rsi
    hostname: be-analyse_data_4h_very-low-rsi
    image: amrox/greencandle
    entrypoint: /docker-entrypoint-data.sh analyse_data
    logging:
      driver: journald
    links:
      - base-mysql-local:mysql
      - base-redis-local:redis
      - be-get_data_4h:data
    depends_on:
      - base-mysql-local
      - base-redis-local
      - be-get_data_4h
    environment:
      - CONFIG_ENV=test/data/long2
      - HOST=$HOSTNAME
    healthcheck:
      test: find /var/run/  -mmin -2 -name greencandle 2>&1 |grep -q greencandle ||exit 1
      interval: 1m
      timeout: 2s
      retries: 5
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run/systemd/journal/socket:/var/run/systemd/journal/socket

  be-get_data_4h:
    container_name: be-get_data_4h
    hostname: be-get_data_4h
    image: amrox/greencandle
    entrypoint: /docker-entrypoint.sh get_data
    logging:
      driver: journald
    ports:
      - 12345
    links:
      - base-mysql-local:mysql
      - base-redis-local:redis
    depends_on:
      - base-mysql-local
      - base-redis-local
    environment:
      - CONFIG_ENV=test/data/long1
      - HOST=$HOSTNAME
    healthcheck:
      test: find /var/run/  -mmin -2 -name greencandle 2>&1 |grep -q greencandle ||exit 1
      interval: 1m
      timeout: 2s
      retries: 5
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run/systemd/journal/socket:/var/run/systemd/journal/socket

  fe-cron:
    container_name: fe-cron
    environment:
      - CONFIG_ENV=test/cron
      - HOST=$HOSTNAME
    hostname: fe-cron
    image: amrox/greencandle
    restart: always
    entrypoint: /docker-entrypoint.sh cron -f
    links:
      - base-mysql-local:mysql
      - base-redis-local:redis
    depends_on:
      - base-mysql-local
      - base-redis-local
    healthcheck:
      test: find /var/run/  -mmin -2 -name cron 2>&1 |grep -q cron ||exit 1
      interval: 1m
      timeout: 2s
      retries: 5
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws

  base-redis-local:
    container_name: base-redis-local
    hostname: base-redis-local
    image: amrox/gc-redis
    ports:
      - 6379:6379
    restart: always
    links:
      - base-mysql-local:mysql
    healthcheck:
      test: redis-cli ping
      interval: 1m
      timeout: 2s
      retries: 5

  base-mysql-local:
    container_name: base-mysql-local
    hostname: base-mysql-local
    image: amrox/gc-mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - CONFIG_ENV=test
    restart: always
    healthcheck:
      test: echo 'SELECT version();'| mysql -uroot -ppassword
      interval: 1m
      timeout: 2s
      retries: 5
