FROM amrox/greencandle:latest
LABEL branch=${BRANCH}
LABEL commit=${COMMIT}
LABEL date=${DATE}

ARG BRANCH="master"
ARG COMMIT=""
ARG DATE=""

ENV COMMIT_SHA=${COMMIT}
ENV VERSION=${BRANCH}
ENV BUILD_DATE=${DATE}

CMD /docker-entrypoint.sh cron -f
