version: "3.7"
services:

  ###### Start Gen

  per-gen-be-logwatch:
    container_name: per-gen-be-logwatch
    hostname: per-gen-be-logwatch
    image: amrox/greencandle:${TAG}
    mem_limit: 200m
    restart: always
    entrypoint: /docker-entrypoint.sh /usr/local/bin/logwatch
    environment:
      - CONFIG_ENV=per/fe/cron
      - DB=false
    volumes:
      - /var/log:/var/log
      - /root/.aws:/root/.aws
      - /var/run:/var/run
    healthcheck:
      test: ls /var/log/syslog
      interval: 1m
      timeout: 10s
      retries: 5

  per-gen-be-logtailer-api:
    container_name: per-gen-be-logtailer-api
    hostname: per-gen-be-logtailer-api
    image: amrox/greencandle:${TAG}
    mem_limit: 300m
    pull_policy: always
    restart: always
    environment:
      - CONFIG_ENV=per
      - DB=false
      - SECRET_KEY=$SECRET_KEY
    entrypoint: /docker-entrypoint.sh logtailer
    logging:
      driver: journald
    ports:
      - 2000
    links:
      - per-base-mysql:mysql
      - per-base-redis:redis
    healthcheck:
      test: ls ||exit 1
      interval: 1m
      timeout: 10s
      retries: 5
    volumes:
      - /var/log/syslog:/var/log/syslog
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run:/var/run
      - /root/.bash_history:/root/.bash_history

  ###### Start Per
  per-base-redis:
    container_name: per-base-redis
    hostname: per-base-redis
    image: amrox/gc-redis:${TAG}
    mem_limit: 300m
    pull_policy: always
    restart: always
    links:
      - per-base-mysql:mysql
    ports:
      - 6380:6379
    healthcheck:
      test: redis-cli ping
      interval: 1m
      timeout: 10s
      retries: 5
    volumes:
      - /var/run:/var/run
      - /root/.aws:/root/.aws
      - /root/.bash_history:/root/.bash_history

  per-base-mysql:
    container_name: per-base-mysql
    hostname: per-base-mysql
    image: amrox/gc-mysql:${TAG}
    mem_limit: 300m
    pull_policy: always
    entrypoint: /docker-entrypoint.sh "--max-connections=10000"
    environment:
      - CONFIG_ENV=per
      - MYSQL_ROOT_PASSWORD=password
      - DB=true
    restart: always
    ports:
      - 3307:3306
    healthcheck:
      test: echo 'SELECT version();'| mysql -uroot -ppassword
      interval: 1m
      timeout: 10s
      retries: 5
    volumes:
      - /var/run/systemd/journal/socket:/var/run/systemd/journal/socket
      - /root/.aws:/root/.aws
      - /root/.bash_history:/root/.bash_history

  per-be-manual:
    container_name: per-be-manual
    hostname: per-be-manual
    environment:
      - CONFIG_ENV=per/be/manual
      - DB=true
    image: amrox/greencandle:${TAG}
    mem_limit: 500m
    pull_policy: always
    restart: always
    entrypoint: /docker-entrypoint.sh "tail -f /dev/null"
    logging:
      driver: journald
    links:
      - per-base-mysql:mysql
      - per-base-redis:redis
      - per-be-api-router:router
    depends_on:
      - per-base-mysql
      - per-base-redis
    healthcheck:
      test: ls || exit 1
      interval: 1m
      timeout: 10s
      retries: 5
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws
      - /var/run:/var/run
      - /dev/log:/dev/log
      - /root/.bash_history:/root/.bash_history
      - /root/.ipython:/root/.ipython

  per-fe-cron:
    container_name: per-fe-cron
    hostname: per-fe-cron
    environment:
      - VPN_IP=$VPN_IP
      - CONFIG_ENV=per/fe/cron
      - DB=true
    image: amrox/greencandle:${TAG}
    mem_limit: 400m
    pull_policy: always
    restart: always
    entrypoint: /docker-entrypoint.sh "cron -f"
    logging:
      driver: journald
    links:
      - per-base-mysql:mysql
      - per-base-redis:redis
    depends_on:
      - per-base-mysql
      - per-base-redis
    healthcheck:
      test: find /var/run/  -mmin -2 -name cron 2>&1 |grep -q cron ||exit 1
      interval: 1m
      timeout: 10s
      retries: 5
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/log:/dev/log
      - /root/.bash_history:/root/.bash_history

  per-fe-webserver:
    container_name: per-fe-webserver
    hostname: per-fe-webserver
    image: amrox/webserver:${TAG}
    mem_limit: 200m
    pull_policy: always
    restart: always
    healthcheck:
      test: curl -Isf 127.1:4444
      interval: 5m
      timeout: 5s
      retries: 5
    environment:
      - CONFIG_ENV=per
      - DB=false
    ports:
      - 4444:4444
    links:
      - per-fe-api-dashboard:api_dash
      - per-base-mysql:mysql
      - per-base-redis:redis
      - per-gen-be-logtailer-api:logs
      - per-fe-api-proxy:proxy
    depends_on:
      - per-base-mysql
      - per-base-redis
    entrypoint: /docker-entrypoint.sh "nginx -g 'daemon off;'"
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws
      - /root/.bash_history:/root/.bash_history
      - /var/run:/var/run
      - /var/local:/var/local

  per-fe-api-proxy:
    container_name: per-fe-api-proxy
    hostname: per-fe-api-proxy
    environment:
      - CONFIG_ENV=per/fe/api
      - SECRET_KEY=$SECRET_KEY
    logging:
      driver: journald
    image: amrox/greencandle:${TAG}
    mem_limit: 200m
    pull_policy: always
    restart: always
    entrypoint: /docker-entrypoint.sh api_proxy
    healthcheck:
      test: curl -qsf http://127.1:5000 >/dev/null
      interval: 1m
      timeout: 10s
      retries: 5
    links:
      - per-be-api-router:router
      - per-fe-api-filesystem:filesystem
    ports:
      - 5000
    depends_on:
      - per-base-mysql
      - per-base-redis
    volumes:
      - /data:/data
      - /dev/log:/dev/log
      - /root/.aws:/root/.aws
      - /var/run:/var/run
      - /root/.bash_history:/root/.bash_history

  per-fe-api-filesystem:
    container_name: per-fe-api-filesystem
    hostname: per-fe-api-filesystem
    environment:
      - CONFIG_ENV=per/fe/api
      - SECRET_KEY=$SECRET_KEY
    logging:
      driver: journald
    image: amrox/greencandle:${TAG}
    mem_limit: 200m
    pull_policy: always
    restart: always
    entrypoint: /docker-entrypoint.sh filesystem_api
    healthcheck:
      test: curl -Isf http://127.1:6000
      interval: 1m
      timeout: 10s
      retries: 5
    ports:
      - 6000
    volumes:
      - /data:/data
      - /dev/log:/dev/log
      - /root/.aws:/root/.aws
      - /var/run:/var/run

  per-fe-api-dashboard:
    container_name: per-fe-api-dashboard
    hostname: per-fe-api-dashboard
    environment:
      - VPN_IP=$VPN_IP
      - CONFIG_ENV=per/fe/api
      - DB=true
      - SECRET_KEY=$SECRET_KEY
    logging:
      driver: journald
    image: amrox/greencandle:${TAG}
    mem_limit: 400m
    pull_policy: always
    restart: always
    entrypoint: /docker-entrypoint.sh api_dashboard
    links:
      - per-base-mysql:mysql
      - per-base-redis:redis
      - per-be-api-router:router
      - per-fe-api-filesystem:filesystem
      - per-fe-api-proxy:proxy
    ports:
      - 5000
    depends_on:
      - per-base-mysql
      - per-base-redis
    healthcheck:
      test: curl -Isf http://127.1:5000/healthcheck
      interval: 1m
      timeout: 10s
      retries: 5
    volumes:
      - /data:/data
      - /dev/log:/dev/log
      - /root/.aws:/root/.aws
      - /var/run:/var/run
      - /root/.bash_history:/root/.bash_history

  per-be-api-router:
    container_name: per-be-api-router
    hostname: per-be-api-router
    image: amrox/greencandle:${TAG}
    mem_limit: 200m
    pull_policy: always
    restart: always
    extra_hosts:
      - "alert:172.31.15.59"
    healthcheck:
      test: curl -Isf http://127.1:1080/healthcheck
      interval: 5m
      timeout: 5s
      retries: 5
    environment:
      - CONFIG_ENV=per/fe/api
      - ALERT="True"
      - DB=true
    ports:
      - 1081:1080
    links:
      - per-base-mysql:mysql
      - per-base-redis:redis
      - per-be-api-any-spot-long:per-be-api-any-spot-long
      - per-be-api-any-cross-long:per-be-api-any-cross-long
      - per-be-api-any-cross-short:per-be-api-any-cross-short
    depends_on:
      - per-base-mysql
      - per-base-redis
      - per-be-api-any-spot-long
      - per-be-api-any-cross-long
    entrypoint: /docker-entrypoint.sh api_router
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws
      - /var/run:/var/run
      - /var/local:/var/local
      - /root/.bash_history:/root/.bash_history

  per-be-api-any-spot-long:
    container_name: per-be-api-any-spot-long
    hostname: per-be-api-any-spot-long
    image: amrox/greencandle:${TAG}
    mem_limit: 400m
    pull_policy: always
    restart: always
    entrypoint: /docker-entrypoint.sh "backend_api api & backend_api queue"
    logging:
      driver: journald
    environment:
      - VPN_IP=$VPN_IP
      - CONFIG_ENV=per/be/any/spot-long
      - DB=true
    ports:
      - 20000
    links:
      - per-base-mysql:mysql
      - per-base-redis:redis
    depends_on:
      - per-base-mysql
      - per-base-redis
    healthcheck:
      test: api_healthcheck.sh || exit 1
      interval: 1m
      timeout: 10s
      retries: 5
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run:/var/run
      - /var/local:/var/local
      - /root/.bash_history:/root/.bash_history

  per-be-api-any-cross-long:
    container_name: per-be-api-any-cross-long
    hostname: per-be-api-any-cross-long
    image: amrox/greencandle:${TAG}
    mem_limit: 400m
    pull_policy: always
    restart: always
    entrypoint: /docker-entrypoint.sh "backend_api api & backend_api queue"
    logging:
      driver: journald
    environment:
      - VPN_IP=$VPN_IP
      - CONFIG_ENV=per/be/any/cross-long
      - DB=true
    ports:
      - 20000
    links:
      - per-base-mysql:mysql
      - per-base-redis:redis
    depends_on:
      - per-base-mysql
      - per-base-redis
    healthcheck:
      test: api_healthcheck.sh || exit 1
      interval: 1m
      timeout: 10s
      retries: 5
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run:/var/run
      - /var/local:/var/local
      - /root/.bash_history:/root/.bash_history

  per-be-api-any-cross-short:
    container_name: per-be-api-any-cross-short
    hostname: per-be-api-any-cross-short
    image: amrox/greencandle:${TAG}
    mem_limit: 400m
    pull_policy: always
    restart: always
    entrypoint: /docker-entrypoint.sh "backend_api api & backend_api queue"
    logging:
      driver: journald
    environment:
      - VPN_IP=$VPN_IP
      - CONFIG_ENV=per/be/any/cross-short
      - DB=true
    ports:
      - 20000
    links:
      - per-base-mysql:mysql
      - per-base-redis:redis
    depends_on:
      - per-base-mysql
      - per-base-redis
    healthcheck:
      test: api_healthcheck.sh || exit 1
      interval: 1m
      timeout: 10s
      retries: 5
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run:/var/run
      - /var/local:/var/local
      - /root/.bash_history:/root/.bash_history
