FROM python:3.6.9
LABEL branch=${BRANCH}
LABEL commit=${COMMIT}
LABEL date=${DATE}

ADD . /install
RUN bash /install/install/gc-install.sh
COPY install/docker-entrypoint.sh /
COPY config /opt/config
RUN chmod +x /docker-entrypoint.sh
HEALTHCHECK CMD find /var/run/  -mmin -2 -name greencandle 2>&1 |grep -q greencandle ||exit 1

ARG BRANCH="master"
ARG COMMIT=""
ARG DATE=""

# Now set it as an env var
ENV COMMIT_SHA=${COMMIT}
ENV VERSION=${BRANCH}
ENV BUILD_DATE=${DATE}

CMD ["/docker-entrypoint.sh"]
