version: "3.1"
services:

  cadvisor:
    container_name: cadvisor
    hostname: cadvisor
    image: gcr.io/google_containers/cadvisor:v0.35.0
    restart: on-failure
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs
      - /var/run:/var/run
      - /sys:/sys
      - /var/lib/docker:/var/lib/docker
      - /dev/disk:/dev/disk

  2ma-btc:
    container_name: 2ma-btc
    hostname: 2ma-btc
    image: greencandle
    entrypoint: /docker-entrypoint.sh backend_test -d /data/altcoin_historical/2019/year/ -s -p BNBBTC -i 4h
    logging:
      driver: journald
    links:
      - mysql-local:mysql
      - redis-local:redis
    depends_on:
      - mysql-local
      - redis-local
    environment:
      - CONFIG_ENV=test/2MA/BTC
      - HOST=$HOSTNAME
    healthcheck:
      test: find /var/run/  -mmin -2 -name greencandle 2>&1 |grep -q greencandle ||exit 1
      interval: 1m
      timeout: 2s
      retries: 5
    volumes:
      - ./test:/tmp
      - /data:/data
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run/systemd/journal/socket:/var/run/systemd/journal/socket

  cron:
    container_name: cron
    environment:
      - CONFIG_ENV=test/cron
      - HOST=$HOSTNAME
    hostname: cron
    image: greencandle
    restart: on-failure
    entrypoint: /docker-entrypoint.sh cron -f
    links:
      - mysql-local:mysql
      - redis-local:redis
    depends_on:
      - mysql-local
      - redis-local
    healthcheck:
      test: find /var/run/  -mmin -2 -name cron 2>&1 |grep -q cron ||exit 1
      interval: 1m
      timeout: 2s
      retries: 5
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws

  api:
    container_name: api
    environment:
      - CONFIG_ENV=test
      - HOST=$HOSTNAME
    hostname: api
    image: greencandle
    restart: on-failure
    entrypoint: /docker-entrypoint-api.sh api --test
    links:
      - mysql-local:mysql
      - redis-local:redis
    ports:
      - 5000:5000
    depends_on:
      - mysql-local
      - redis-local
    healthcheck:
      test: find /var/run/  -mmin -2 -name api 2>&1 |grep -q api || exit 1
      interval: 1m
      timeout: 2s
      retries: 5
    volumes:
      - /data:/data

  webserver:
     container_name: webserver
     hostname: webserver
     image: webserver
     entrypoint: /docker-entrypoint.sh nginx -g 'daemon off;'
     healthcheck:
       test: service nginx status || exit 1
       interval: 1m
       timeout: 1s
       retries: 5
     environment:
       - CONFIG_ENV=test
       - HOST=$HOSTNAME
     ports:
       - 7777:7777
     links:
       - mysql-local:mysql
       - redis-local:redis
       - dashboard:dashboard
       - api
     restart: on-failure
     volumes:
       - /data:/data
       - /root/.aws:/root/.aws
     depends_on:
      - cadvisor
      - api
      - dashboard
    

  dashboard:
    container_name: dashboard
    hostname: dashboard
    image: dashboard
    healthcheck:
      test: curl --fail 127.1:3030/dashboard/gc || exit 1
      interval: 1m
      timeout: 5s
      retries: 5
    ports:
      - 3030:3030
    restart: on-failure
    entrypoint: /docker-entrypoint.sh
    links:
      - mysql-local:mysql
      - redis-local:redis
    volumes:
      - /srv/greencandle/dashboard/dashboards:/dashboards
      - /srv/greencandle/dashboard/jobs:/jobs
      - /srv/greencandle/dashboard/widgets:/widgets
      - /srv/greencandle/dashboard/config:/config
      - /srv/greencandle/dashboard/assets:/assets

  redis-local:
    container_name: redis-local
    hostname: redis-local
    image: gc-redis
    ports:
      - 6379:6379
    restart: on-failure
    links:
      - mysql-local:mysql
    healthcheck:
      test: redis-cli ping
      interval: 1m
      timeout: 2s
      retries: 5

  mysql-local:
    container_name: mysql-local
    hostname: mysql-local
    image: gc-mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - CONFIG_ENV=test
    restart: on-failure
    healthcheck:
      test: echo 'SELECT version();'| mysql -uroot -ppassword
      interval: 1m
      timeout: 2s
      retries: 5

  greencandle-unittest:
    container_name: unittest
    hostname: unittest
    image: greencandle
    entrypoint: /docker-entrypoint.sh python -m unittest
    links:
      - mysql-local:mysql
      - redis-local:redis
    working_dir: /srv/greencandle
    depends_on:
      - redis-local
      - mysql-local
    environment:
      - CONFIG_ENV=test/unit
    volumes:
      - ../:/srv/greencandle
