version: "3.1"
services:

  dev-fe-cron:
    container_name: dev-fe-cron
    hostname: dev-fe-cron
    environment:
      - CONFIG_ENV=dev
      - DB=true
    image: amrox/greencandle:${TAG}
    restart: always
    entrypoint: /docker-entrypoint.sh "cron -f"
    links:
      - dev-base-mysql:mysql
      - dev-base-redis:redis
    depends_on:
      - dev-base-mysql
      - dev-base-redis
    healthcheck:
      test: ls || exit 1
      interval: 1m
      timeout: 10s
      retries: 5
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws

  dev-be-manual:
    container_name: dev-be-manual
    environment:
      - CONFIG_ENV=dev
      - DB=true
    hostname: dev-be-manual
    image: amrox/greencandle:${TAG}
    restart: always
    entrypoint: /docker-entrypoint.sh "tail -f /dev/null"
    links:
      - dev-base-mysql:mysql
      - dev-base-redis:redis
      - dev-be-stream_1m:stream
    depends_on:
      - dev-base-mysql
      - dev-base-redis
    healthcheck:
      test: ls || exit 1
      interval: 1m
      timeout: 10s
      retries: 5
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws

  dev-base-redis:
    container_name: dev-base-redis
    hostname: dev-base-redis
    image: amrox/gc-redis:${TAG}
    ports:
      - 6379
    environment:
      - CONFIG_ENV=dev
    restart: always
    links:
      - dev-base-mysql:mysql
    entrypoint: /docker-entrypoint.sh redis-server /etc/redis.conf
    healthcheck:
      test: redis-cli ping
      interval: 1m
      timeout: 10s
      retries: 5

  dev-base-mysql:
    container_name: dev-base-mysql
    hostname: dev-base-mysql
    image: amrox/gc-mysql:${TAG}
    ports:
      - 3302:3306
    entrypoint: /docker-entrypoint.sh mysqld
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - CONFIG_ENV=dev
      - DB=true
    restart: always
    healthcheck:
      test: echo 'SELECT version();'| mysql -uroot -ppassword
      interval: 1m
      timeout: 10s
      retries: 5

  dev-be-stream_1m:
    container_name: dev-be-stream_1m
    hostname: dev-be-stream_1m
    image: amrox/greencandle:${TAG}
    mem_limit: 200m
    pull_policy: always
    restart: always
    entrypoint: /docker-entrypoint.sh stream_data
    logging:
      driver: journald
    links:
      - dev-base-mysql:mysql
      - dev-base-redis:redis
    depends_on:
      - dev-base-mysql
      - dev-base-redis
    environment:
      - VPN_IP=$VPN_IP
      - CONFIG_ENV=dev
      - DB=true
    healthcheck:
      test: echo || exit 1
      start_period: 1m
      interval: 1m
      timeout: 10s
      retries: 5
    ports:
      - 5000
    volumes:
      - /mnt:/mnt
      - /data:/data
      - /var/local:/var/local
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run/:/var/run

  dev-be-analyse-1m-short1:
    container_name: dev-be-analyse-1m-short1
    hostname: dev-be-analyse-1m-short1
    image: amrox/greencandle:${TAG}
    mem_limit: 500m
    pull_policy: always
    restart: always
    entrypoint: /docker-entrypoint.sh "analyse_data"
    logging:
      driver: journald
    links:
      - dev-be-api-router:router
      - dev-base-mysql:mysql
      - dev-base-redis:redis
    depends_on:
      - dev-base-mysql
      - dev-base-redis
      - dev-be-get_1m
    environment:
      - VPN_IP=$VPN_IP
      - ALERT=True
      - STORE_IN_DB=True
      - CONFIG_ENV=dev
      - DB=true
    healthcheck:
      test: find /var/local/  -mmin -2 -name greencandle 2>&1 |grep -q greencandle ||exit 1
      start_period: 1h
      interval: 1m
      timeout: 10s
      retries: 5
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run/:/var/run

  dev-be-get_1m:
    container_name: dev-be-get_1m
    hostname: dev-be-get_1m
    image: amrox/greencandle:${TAG}
    mem_limit: 1000m
    pull_policy: always
    restart: always
    entrypoint: /docker-entrypoint.sh get_data
    logging:
      driver: journald
    links:
      - dev-base-mysql:mysql
      - dev-base-redis:redis
      - dev-be-stream_1m:stream
    depends_on:
      - dev-base-mysql
      - dev-base-redis
    environment:
      - VPN_IP=$VPN_IP
      - CONFIG_ENV=dev
      - DB=true
    healthcheck:
      test: find /var/local/lock/gc_get_1m.lock  -mmin -2 ||exit 1
      interval: 1m
      timeout: 10s
      retries: 5
    volumes:
      - /data:/data
      - /var/local:/var/local
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run/:/var/run

  dev-be-api-router:
    container_name: dev-be-api-router
    hostname: dev-be-api-router
    extra_hosts:
      - "alert:10.8.0.104"
    image: amrox/greencandle:${TAG}
    mem_limit: 200m
    pull_policy: always
    restart: always
    healthcheck:
      test: curl -Isf http://127.1:1080/healthcheck
      interval: 5m
      timeout: 5s
      retries: 5
    environment:
      - CONFIG_ENV=dev
      - DB=true
    ports:
      - 1083:1080
    links:
      - dev-base-mysql:mysql
      - dev-base-redis:redis
    depends_on:
      - dev-base-mysql
      - dev-base-redis
    entrypoint: /docker-entrypoint.sh api_router
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws
      - /var/run:/var/run
      - /var/local:/var/local
      - /root/.bash_history:/root/.bash_history


