version: "3.1"
services:

  gen-fe-cadvisor:
    container_name: gen-fe-cadvisor
    hostname: gen-fe-cadvisor
    image: gcr.io/google_containers/cadvisor:v0.35.0
    restart: always
    volumes:
      - /:/rootfs
      - /var/run:/var/run
      - /sys:/sys
      - /var/lib/docker:/var/lib/docker
      - /dev/disk:/dev/disk
    healthcheck:
      test: "printf 'GET /healthz HTTP/1.1\r\nHost: localhost\r\n\r\n' | nc localhost 8080"
      interval: 1m
      timeout: 2s
      retries: 5

  test-base-redis:
    container_name: test-base-redis
    hostname: test-base-redis
    image: amrox/gc-redis:${TAG}
    pull_policy: always
    restart: always
    links:
      - test-base-mysql:mysql
    ports:
      - 6378:6379
    healthcheck:
      test: redis-cli ping
      interval: 1m
      timeout: 2s
      retries: 5
    volumes:
      - /var/run/systemd/journal/socket:/var/run/systemd/journal/socket
      - /root/.aws:/root/.aws
      - /root/.bash_history:/root/.bash_history

  test-base-mysql:
    container_name: test-base-mysql
    hostname: test-base-mysql
    image: amrox/gc-mysql:${TAG}
    entrypoint: /docker-entrypoint.sh mysqld
    pull_policy: always
    environment:
      - CONFIG_ENV=test
      - MYSQL_ROOT_PASSWORD=password
    restart: always
    ports:
      - 3305:3306
    healthcheck:
      test: echo 'SELECT version();'| mysql -uroot -ppassword
      interval: 1m
      timeout: 2s
      retries: 5
    volumes:
      - /var/run/systemd/journal/socket:/var/run/systemd/journal/socket
      - /root/.aws:/root/.aws
      - /root/.bash_history:/root/.bash_history

  test-fe-api-dashboard:
    container_name: test-fe-api-dashboard
    hostname: test-fe-api-dashboard
    environment:
      - CONFIG_ENV=test/fe/api
      - HOST=$HOSTNAME
    logging:
      driver: journald
    image: amrox/greencandle:${TAG}
    pull_policy: always
    restart: always
    entrypoint: /docker-entrypoint-api.sh api_dashboard
    links:
      - test-base-mysql:mysql
      - test-base-redis:redis
      - test-be-api-router:router
    ports:
      - 5000
    depends_on:
      - test-base-mysql
      - test-base-redis
    healthcheck:
      test: curl -Isf http://127.1:5000/healthcheck
      interval: 1m
      timeout: 2s
      retries: 5
    volumes:
      - /data:/data
      - /dev/log:/dev/log
      - /root/.aws:/root/.aws
      - /var/run/systemd/journal/socket:/var/run/systemd/journal/socket
      - /root/.bash_history:/root/.bash_history

  test-fe-cron:
    container_name: test-fe-cron
    hostname: test-fe-cron
    environment:
      - CONFIG_ENV=test/fe/cron
      - HOST=$HOSTNAME
    image: amrox/greencandle:${TAG}
    pull_policy: always
    restart: always
    entrypoint: /docker-entrypoint.sh cron -f
    logging:
      driver: journald
    links:
      - test-base-mysql:mysql
      - test-base-redis:redis
    depends_on:
      - test-base-mysql
      - test-base-redis
    healthcheck:
      test: find /var/run/  -mmin -2 -name cron 2>&1 |grep -q cron ||exit 1
      interval: 1m
      timeout: 2s
      retries: 5
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/log:/dev/log
      - /var/run/systemd/journal/socket:/var/run/systemd/journal/socket
      - /root/.bash_history:/root/.bash_history

  test-fe-webserver:
    container_name: test-fe-webserver
    hostname: test-fe-webserver
    image: amrox/webserver:${TAG}
    pull_policy: always
    restart: always
    healthcheck:
      test: service nginx status || exit 1
      interval: 5m
      timeout: 5s
      retries: 5
    environment:
      - CONFIG_ENV=test
      - HOST=$HOSTNAME
    ports:
      - 8888:8888
    links:
      - gen-fe-cadvisor:cadvisor
      - test-fe-api-dashboard:api_dash
      - test-be-logtailer:logs
      - test-base-mysql:mysql
      - test-base-redis:redis
    depends_on:
      - gen-fe-cadvisor
      - test-base-mysql
      - test-base-redis
    entrypoint: /docker-entrypoint.sh nginx -g 'daemon off;'
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws
      - /root/.bash_history:/root/.bash_history

  test-fe-api-web:
    container_name: test-fe-api-web
    hostname: test-fe-api-web
    image: amrox/webserver:${TAG}
    pull_policy: always
    restart: always
    healthcheck:
      test: service nginx status || exit 1
      interval: 5m
      timeout: 5s
      retries: 5
    environment:
      - CONFIG_ENV=test/fe/api
      - HOST=$HOSTNAME
    ports:
      - 1111:1111
    links:
      - test-be-api-router:router
      - test-base-mysql:mysql
      - test-base-redis:redis
    depends_on:
      - test-base-mysql
      - test-base-redis
    entrypoint: /docker-entrypoint-api2.sh nginx -g 'daemon off;'
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws
      - /root/.bash_history:/root/.bash_history

  test-be-api-router:
    container_name: test-be-api-router
    hostname: test-be-api-router
    image: amrox/greencandle:${TAG}
    pull_policy: always
    restart: always
    extra_hosts:
      - "alert:10.8.0.1"
    healthcheck:
      test: curl -Isf http://127.1:1080/healthcheck
      interval: 5m
      timeout: 5s
      retries: 5
    environment:
      - CONFIG_ENV=test
      - HOST=$HOSTNAME
    ports:
      - 1080:1080
    links:
      - test-base-mysql:mysql
      - test-base-redis:redis
      - test-be-any-long:any-long
      - test-be-any-short:any-short
      - test-be-any-spot-long:any-spot-long
    depends_on:
      - test-base-mysql
      - test-base-redis
    entrypoint: /docker-entrypoint.sh api_router --test
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws
      - /var/run:/var/run
      - /root/.bash_history:/root/.bash_history

  test-be-5ma-api-btc:
    container_name: test-be-5ma-api-btc
    hostname: test-be-5ma-api-btc
    image: amrox/greencandle:${TAG}
    pull_policy: always
    restart: always
    entrypoint: /docker-entrypoint.sh backend_api --test
    logging:
      driver: journald
    environment:
      - HOST=$HOSTNAME
      - CONFIG_ENV=test/5MA/api/btc
      - HOST_IP=$HOST_IP
      - VPN_IP=$VPN_IP
      - GC_PORT=8888
    ports:
      - 20000
    links:
      - test-base-mysql:mysql
      - test-base-redis:redis
    depends_on:
      - test-base-mysql
      - test-base-redis
    healthcheck:
      test: ls ||exit 1
      interval: 1m
      timeout: 2s
      retries: 5
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run/systemd/journal/socket:/var/run/systemd/journal/socket
      - /root/.bash_history:/root/.bash_history

  test-be-5ma-api-usdt:
    container_name: test-be-5ma-api-usdt
    hostname: test-be-5ma-api-usdt
    image: amrox/greencandle:${TAG}
    pull_policy: always
    restart: always
    entrypoint: /docker-entrypoint.sh backend_api --test
    logging:
      driver: journald
    environment:
      - GC_PORT=8888
      - VPN_IP=$VPN_IP
      - HOST=$HOSTNAME
      - CONFIG_ENV=test/5MA/api/usdt
      - HOST_IP=$HOST_IP
    ports:
      - 20000
    links:
      - test-base-mysql:mysql
      - test-base-redis:redis
    depends_on:
      - test-base-mysql
      - test-base-redis
    healthcheck:
      test: ls ||exit 1
      interval: 1m
      timeout: 2s
      retries: 5
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run/systemd/journal/socket:/var/run/systemd/journal/socket
      - /root/.bash_history:/root/.bash_history

  test-be-5ma-api-eth:
    container_name: test-be-5ma-api-eth
    hostname: test-be-5ma-api-eth
    image: amrox/greencandle:${TAG}
    pull_policy: always
    restart: always
    entrypoint: /docker-entrypoint.sh backend_api --test
    logging:
      driver: journald
    environment:
      - VPN_IP=$VPN_IP
      - GC_PORT=8888
      - HOST=$HOSTNAME
      - CONFIG_ENV=test/5MA/api/eth
      - HOST_IP=$HOST_IP
    ports:
      - 20000
    links:
      - test-base-mysql:mysql
      - test-base-redis:redis
    depends_on:
      - test-base-mysql
      - test-base-redis
    healthcheck:
      test: ls ||exit 1
      interval: 1m
      timeout: 2s
      retries: 5
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run/systemd/journal/socket:/var/run/systemd/journal/socket
      - /root/.bash_history:/root/.bash_history

  test-be-any-spot-long:
    container_name: test-be-any-spot-long
    hostname: test-be-any-spot-long
    image: amrox/greencandle:${TAG}
    pull_policy: always
    restart: always
    entrypoint: /docker-entrypoint.sh backend_api --test
    logging:
      driver: journald
    environment:
      - VPN_IP=$VPN_IP
      - GC_PORT=8888
      - HOST=$HOSTNAME
      - CONFIG_ENV=test/any/spot
      - HOST_IP=$HOST_IP
      - get_trend="true"
      - intermittent="true"
    extra_hosts:
      - "trend:10.8.0.101"
    ports:
      - 20000
    links:
      - test-base-mysql:mysql
      - test-base-redis:redis
    depends_on:
      - test-base-mysql
      - test-base-redis
    healthcheck:
      test: ls ||exit 1
      interval: 1m
      timeout: 2s
      retries: 5
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run/systemd/journal/socket:/var/run/systemd/journal/socket
      - /root/.bash_history:/root/.bash_history

  test-be-any-long:
    container_name: test-be-any-long
    hostname: test-be-any-long
    image: amrox/greencandle:${TAG}
    pull_policy: always
    restart: always
    entrypoint: /docker-entrypoint.sh backend_api --test
    logging:
      driver: journald
    environment:
      - VPN_IP=$VPN_IP
      - GC_PORT=8888
      - HOST=$HOSTNAME
      - CONFIG_ENV=test/any
      - HOST_IP=$HOST_IP
      - get_trend="true"
      - intermittent="true"
    extra_hosts:
      - "trend:10.8.0.101"
    ports:
      - 20000
    links:
      - test-base-mysql:mysql
      - test-base-redis:redis
    depends_on:
      - test-base-mysql
      - test-base-redis
    healthcheck:
      test: ls ||exit 1
      interval: 1m
      timeout: 2s
      retries: 5
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run/systemd/journal/socket:/var/run/systemd/journal/socket
      - /root/.bash_history:/root/.bash_history

  test-be-any-long:
    container_name: test-be-any-long
    hostname: test-be-any-long
    image: amrox/greencandle:${TAG}
    pull_policy: always
    restart: always
    entrypoint: /docker-entrypoint.sh backend_api --test
    logging:
      driver: journald
    environment:
      - VPN_IP=$VPN_IP
      - GC_PORT=8888
      - HOST=$HOSTNAME
      - CONFIG_ENV=test/any
      - HOST_IP=$HOST_IP
      - get_trend="true"
      - intermittent="true"
    extra_hosts:
      - "trend:10.8.0.101"
    ports:
      - 20000
    links:
      - test-base-mysql:mysql
      - test-base-redis:redis
    depends_on:
      - test-base-mysql
      - test-base-redis
    healthcheck:
      test: ls ||exit 1
      interval: 1m
      timeout: 2s
      retries: 5
    volumes:
      - /data:/data
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run/systemd/journal/socket:/var/run/systemd/journal/socket
      - /root/.bash_history:/root/.bash_history

  test-be-logtailer:
    container_name: test-be-logtailer
    hostname: test-be-logtailer
    image: amrox/greencandle:${TAG}
    pull_policy: always
    restart: always
    entrypoint: /docker-entrypoint.sh logtailer
    logging:
      driver: journald
    ports:
      - 2222:2222
    healthcheck:
      test: ls ||exit 1
      interval: 1m
      timeout: 2s
      retries: 5
    volumes:
      - /var/log/syslog:/var/log/syslog
      - /root/.aws:/root/.aws
      - /dev/log:/dev/log
      - /var/run/systemd/journal/socket:/var/run/systemd/journal/socket
      - /root/.bash_history:/root/.bash_history
